### ISSUE TITLE
Add support for Microsoft Excel

### ISSUE THREAD

**Issue by Rednas83** [nuxt/content#1002]
### Is your feature request related to a problem? Please describe.
Not able to parse excel files!

### Describe the solution you'd like
Add support for an excel parser like https://github.com/SheetJS/sheetjs to also support **xlsx**

Something like:
`await this.$content(excel).only([sheet]).fetch()`

### Describe alternatives you've considered

- Export all seperate tabs as csv and import with 'content' as array of objects
- Parse with a server api

**Comment by itpropro** [comment]
To be honest, I think supporting a proprietary format that is very uncommon in web development compared to one of the most common file/media format would not really help the module. This would basically mean that the project could be bloated with parsers for countless spreadsheet/table formats.
The much more straight forward approach would be to convert your data from xls/xlsx/csv to json and let nuxt content do the rest.
JSON is the widest and most optimized format for the usecase of nuxt content, which is providing a file system based database to query from. Think of some kind of minimal filesystem based MongoDB implementation.

**Comment by Rednas83** [comment]
Thanks for your honest opinion. I appreciatie it.

Nice thing of sheetjs is that it supports lots of differents spreadsheet programs like XLS(X), DBF, ODS, etc.
https://github.com/SheetJS/sheetjs#file-formats

So perhaps adding 1 parser could be enough? Or perhaps as a seperate extension?

I also just asked for adding nuxt support with the SheetJs library itself. Perhaps this indeed makes more sense.
https://github.com/SheetJS/sheetjs/issues/2496

With SSR it feels a bit strange that I need to manually convert the sheets to csv/json. But perhaps it's just me being lazy🤭

**Comment by reviewher** [comment]
@itpropro this would be feasible as a really short custom parser, but `@nuxt/content` assumes the files contain UTF-8 encoded text: https://github.com/nuxt/content/blob/main/packages/content/lib/database.js#L233

If there were a way for the custom parsers to get the raw content as a buffer, then it would also allow for compressed text files (`.txt.gz`), word processor documents (`.docx`, `.doc`, `.pages`) and other non-plaintext formats.

**Comment by reviewher** [comment]
https://github.com/SheetJS/sheetjs/issues/2496#issuecomment-1062557645

**Comment by Tahul** [comment]
Hello!

This is really interesting, I'm adding both `v1` and `v2` tags.

I think supporting XLSX into @nuxt/content v2 should be possible and definitely be in the roadmap.

Expect updates soon, and thank your for the issue!

**Comment by SheetJSDev** [comment]
In case you need inspiration, our VueJS demo includes a neat example

https://user-images.githubusercontent.com/6070939/157599532-e3978b11-c4be-4873-a2a3-e02e68ad0c3b.mp4

The [`index.vue` page](https://github.com/SheetJS/sheetjs/blob/master/demos/vue/pages/index.vue) is not particularly interesting (it really should just reuse a CSV example)

The [`nuxt.config.js` file](https://github.com/SheetJS/sheetjs/blob/master/demos/vue/nuxt.config.js) uses `extendParser` to listen to a number of file formats.  It generates an array of JS objects per worksheet.

A [sample file](https://github.com/SheetJS/sheetjs/tree/master/demos/vue/content) can be placed in the `content` folder

**Comment by Tahul** [comment]
That is lovely @SheetJSDev ; definitely taking this into consideration to plan xlsx support for @nuxt/content!

**Comment by SheetJSDev** [comment]
Official support would be nice, but it would probably suffice to include some example in the Community Snippets or Integrations section of the documentation.  The SheetJS writeup for this integration was moved to https://docs.sheetjs.com/docs/demos/content#nuxtjs

**Comment by Rednas83** [comment]
Just tried this with **v2**, but unfortunately **extendParser** is not supported (yet). See #1822 for the feature request.

**Comment by SheetJSDev** [comment]
For Nuxt Content v2, it should be doable with custom transformers.  Unfortunately there's a bug with custom transformers, see #1823

**Comment by SheetJSDev** [comment]
@Rednas83 since you asked, https://docs.sheetjs.com/docs/demos/static/nuxtjs/#nuxt-content-v2 (the demo page includes examples for "Nuxt v2 + Nuxt Content v1" and "Nuxt v3 + Nuxt Content v2")

The official Nuxt Content docs should be revisited, as the transformer docs had some errors.

Observing that files placed in the `content` subfolder have the ID `content:${filename}`, it's possible for a transformer to re-read the raw data from the filesystem as a NodeJS Buffer:

```js
import { readFileSync } from "node:fs";
import { resolve } from 'node:path';

const raw_bytes = (id) => readFileSync(resolve("./content/" + id.slice(8)));
```

This is certainly brittle.  If there's a better approach, please comment and we can update our docs.

**Comment by Rednas83** [comment]
For some reason I am not able to import **defineTransformer**
![image](https://user-images.githubusercontent.com/25219229/213864518-97d9f20c-b6c6-43bb-86ad-ba08285ea504.png)

How did you manage to do this or should we wait for the next version of Nuxt Content v2?

Documentation looks great. Perhaps use this command for cleaning the cache in nuxt
`npx nuxi clean|cleanup [rootDir]` instead of `rm -rf .nuxt/content-cache`

**Comment by SheetJSDev** [comment]
The demo works without error.  Updated docs page to use `npx nuxi clean`.

.

The displayed error affects `npx nuxt typecheck` and VSCodium but does not affect the actual build or the generated output.

Based on the docs, you should be able to add an alias to `nuxt.config.ts`:

```ts
export default defineNuxtConfig({
  // ...
    alias: {
    '@nuxt/content/transformers': 'node_modules/@nuxt/content/dist/runtime/transformers'
  }
});
```

That sates the typechecker and VSCodium but breaks `npx yarn run generate`.

The solution will require a patch to `@nuxt/content` and possibly a patch to `nuxt`

**Comment by Rednas83** [comment]
After clean and restart of nuxt the **alias** works
`  alias: {
    '@nuxt/content/transformers': 'node_modules/@nuxt/content/dist/runtime/transformers/utils'
  }`
I also have this in the terminal
![image](https://user-images.githubusercontent.com/25219229/213869172-bc5182d9-a625-405c-a2f3-13dd48ff4995.png)
Resulting in:
![image](https://user-images.githubusercontent.com/25219229/213869192-52133901-a26d-4a01-9276-54c499b318bb.png)

Version info:
NodeJs v18.12.1

**Comment by SheetJSDev** [comment]
That's exactly what happens locally.  If you don't add the alias, the *build* works but the *types* fail.  If you add the alias, the *types* work but the *build* fails (complete showstopper).  Until this is resolved, suppress the type error by adding `// @ts-ignore` just before the import:

```ts
// @ts-ignore
import { defineTransformer } from "@nuxt/content/transformers/utils";
```

**Comment by Rednas83** [comment]
Just tried with the latest version of nuxt, but looks like **xlsx** is not supported anymore😢
![image](https://user-images.githubusercontent.com/25219229/215069685-b61db2f6-3e8a-44e7-8649-2f4ae1f395aa.png)
![image](https://user-images.githubusercontent.com/25219229/215070635-86b99050-9dd3-463e-a4fa-cb3578aa3280.png)

For some reason it also required installing `@types/node`

**Comment by SheetJSDev** [comment]
Raise a new issue. The node types issue affects a blank project:

```bash
npx nuxi init -t content newproject
cd newproject
npx yarn install
npx nuxi typecheck
```

the error looks like

```
Nuxi 3.1.1                                                            06:15:00
error TS2688: Cannot find type definition file for 'node'.
  The file is in the program because:
    Entry point of type library 'node' specified in compilerOptions


Found 1 error.


 ERROR  Command failed with exit code 2: npx -p vue-tsc -p typescript vue-tsc --noEmit

  at makeError (node_modules/nuxi/dist/shared/nuxi.a75c2bed.mjs:619:11)
  at handlePromise (node_modules/nuxi/dist/shared/nuxi.a75c2bed.mjs:1026:26)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async Object.invoke (node_modules/nuxi/dist/chunks/typecheck.mjs:46:7)
  at async _main (node_modules/nuxi/dist/cli.mjs:51:20)
```

**Comment by SheetJSDev** [comment]
Following up here, @danielroe is working on some changes to make `@types/node` a dev dependency in the starter projects.  While we wait for the new starters, you can manually add that module as a dev dependency with `npx yarn add --dev @types/node`

We've added that step [to our demo page](https://docs.sheetjs.com/docs/demos/static/nuxtjs#nuxt-content-2-demo) and the generated project now passes `npx nuxi typecheck`

**Comment by Rednas83** [comment]
Any updates on adding official support for sheetjs? 

It would add support for so much more files
![Image](https://github.com/user-attachments/assets/e50e52c8-6589-46ec-bcc4-aae2e0b7563d)

**Comment by farnabaz** [comment]
With the content v3 there are possibilities for developers to create custom transformers or custom sources. 

for example, some can easily create a [transformer](https://content.nuxt.com/docs/getting-started/configuration#transformers) using `xlsx` package:

```ts
import { defineTransformer } from '@nuxt/content'
import { read, utils } from 'xlsx'

export default defineTransformer({
  name: 'excel-to-json',
  extensions: ['.xlsx'],
  parse(file) {
    const workbook = read(file.body)
    const sheet = workbook.Sheets[workbook.SheetNames[0]]

    const json = utils.sheet_to_json(sheet)
    return {
      id: file.id,
      data: json,
      title: file.title + ' (suffix)',
    }
  },
})
```

Or via [Custom Source](https://content.nuxt.com/docs/advanced/custom-source)

```ts
import { defineCollectionSource } from '@nuxt/content'
import { readFile, utils } from 'xlsx'

const excelSource = defineCollectionSource({
  getKeys: () => {
    const workbook = readFile('path to excel')
    const sheet = workbook.Sheets[workbook.SheetNames[0]]

    const json = utils.sheet_to_json(sheet)
    return json.map(row => row.id)
  },
  getItem: (key: string) => {
    const workbook = readFile('path to excel')
    const sheet = workbook.Sheets[workbook.SheetNames[0]]

    const json = utils.sheet_to_json(sheet)

    return json.find(row => row.id === key)
  },
})
```

Excel files are a whole different world and their content is too dynamic to handle in a generic transformer. (Images, merged cells, links, formulas, ...).

Now that Nuxt Content provides different ways to create custom integrations. We can freely close this issue as there will be no official Excel transformer in Nuxt Content.

**Comment by Rednas83** [comment]
Just tried [transformers](https://content.nuxt.com/docs/getting-started/configuration#transformers), but how to actually call the transformer?

In v2 it was something like
**modules\sheetjs\index.ts**
```
import { resolve } from "path"
import { defineNuxtModule, createResolver } from "@nuxt/kit"
export default defineNuxtModule({
  meta: {
    name: "@nuxtjs/sheetjs",
    configKey: "sheetjs",
    compatibility: { nuxt: ">=3.0.0" },
  },
  setup(options, nuxt) {
    // const { resolve } = createResolver(import.meta.url)
    // https://nuxt.com/docs/api/advanced/hooks
    nuxt.hook("content:context", (contentContext) => {
      contentContext.transformers.push(resolve("modules/sheetjs/sheetjs.ts"))
    })
  },
})
```
But that returns
![Image](https://github.com/user-attachments/assets/9f04caae-99bc-466c-9cc0-9c56a4d4adc4)

How to do it with v3?

Also tried [Custom Source](https://content.nuxt.com/docs/advanced/custom-source)
```
import { defineContentConfig, defineCollectionSource, defineCollection, z } from "@nuxt/content"
import { readFile, utils } from "xlsx"

const pres = defineCollectionSource({
  getKeys: async () => {
    // return fetch("https://hacker-news.firebaseio.com/v0/topstories.json")
    //   .then((res) => res.json())
    //   .then((data) => data.map((key: string) => `${key}.json`))
    const workbook = readFile("./content/pres.xlsx")
    const data = utils.sheet_to_json(workbook["Sheet1"], { header: 1 }) as string[][]
    return data[0] ?? []
  },
  getItem: async (key: string) => {
    const id = key.split(".")[0]
    return fetch(`https://hacker-news.firebaseio.com/v0/item/${id}.json`).then((res) => res.json())
    // const workbook = readFile("./content/pres.xlsx")
    // const data = utils.sheet_to_json(workbook["Sheet1"], { header: 1 }) as string[][]
    // return data[0] ?? ""
  }
})
```

But that returns
![Image](https://github.com/user-attachments/assets/d17607f6-d1a5-4e23-b602-f70d5af035cf)

**Comment by Rednas83** [comment]
Hereby [nuxt-content-sheetjs](https://codesandbox.io/p/devbox/beautiful-sara-gnctrm)
**modules/sheetjsV2** Solution that worked with Nuxt Content V2
**modules/sheetjsV3** via [transformer](https://content.nuxt.com/docs/getting-started/configuration#transformers) returning errors
**content.config.ts** via [Custom Source](https://content.nuxt.com/docs/advanced/custom-source)

Did you also test with local content like **content/pres.xlsx** or just with https://hacker-news.firebaseio.com/v0/topstories.json

Workaround from @SheetJSDev with vite instead of nuxt content
https://docs.sheetjs.com/docs/demos/static/nuxtjs/#nuxt-content-v3

Not sure what the problem is but it looks like external files are not available in the **transformer** or in **content.config.ts**

**Comment by Rednas83** [comment]
Could it be that **content.config.ts** runs on server level and therefore requires an absolute or full path?

Something like
`await fetch('https://hacker-news.firebaseio.com/v0/topstories.json')`
or via a public folder **/public/content/pres.xlsx**
`await $fetch('http://localhost:3000/content/pres.xlsx')`

Can you also provide an example/solution with custom local content?

**Comment by Rednas83** [comment]
Any updates?

**Comment by alex-eri** [comment]
> content.config.ts

this module populates content only at build time. Easier way: not use content module here and render this data with vue component.
