### ISSUE TITLE
Content v2 not working

### ISSUE THREAD

**Issue by bart** [nuxt/content#1106]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.1.0`
- Nuxt Version:     `3.0.0-rc.3`
- Package Manager:  `yarn@1.22.18`
- Builder:          `vite`
- User Config:      `modules`
- Runtime Modules:  `@nuxt/content@2.0.0-27549538.8186622`
- Build Modules:    `-`

### Reproduction

Just follow the Get started guide on https://content-v2.nuxtjs.org/get-started

```
1. npx nuxi init content-app -t content-v2
2. cd content-app
3. yarn install
4. yarn dev
```

### Describe the bug

Getting white screen of death after Nuxt 3 loading animation. Following logs appear in console:

```
[Vue warn]: Failed to resolve component: Content
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
[nitro] [dev] [unhandledRejection] TypeError: Invalid value used as weak map key
    at WeakMap.set (<anonymous>)
    at normalizePropsOptions (/Users/bart/Code/content-app/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:3965:11)
    at createComponentInstance (/Users/bart/Code/content-app/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6951:23)
    at renderComponentVNode (/Users/bart/Code/content-app/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:171:22)
    at Module.ssrRenderComponent (/Users/bart/Code/content-app/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:608:12)
    at _sfc_ssrRender (file:///Users/bart/Code/content-app/.nuxt/dist/server/server.mjs:5371:31)
    at renderComponentSubTree (/Users/bart/Code/content-app/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:253:13)
    at renderComponentVNode (/Users/bart/Code/content-app/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:188:16)
    at renderVNode (/Users/bart/Code/content-app/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:295:22)
    at renderVNode (/Users/bart/Code/content-app/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:301:17)
[Vue warn]: Failed to resolve component: Content
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
[nitro] [dev] [unhandledRejection] TypeError: Invalid value used as weak map key
    at WeakMap.set (<anonymous>)
    at normalizePropsOptions (/Users/bart/Code/content-app/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:3965:11)
    at createComponentInstance (/Users/bart/Code/content-app/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6951:23)
    at renderComponentVNode (/Users/bart/Code/content-app/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:171:22)
    at Module.ssrRenderComponent (/Users/bart/Code/content-app/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:608:12)
    at _sfc_ssrRender (file:///Users/bart/Code/content-app/.nuxt/dist/server/server.mjs:5371:31)
    at renderComponentSubTree (/Users/bart/Code/content-app/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:253:13)
    at renderComponentVNode (/Users/bart/Code/content-app/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:188:16)
    at renderVNode (/Users/bart/Code/content-app/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:295:22)
    at renderVNode (/Users/bart/Code/content-app/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:301:17)
[Vue warn]: Failed to resolve component: Content
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
[nitro] [dev] [unhandledRejection] TypeError: Invalid value used as weak map key
    at WeakMap.set (<anonymous>)
    at normalizePropsOptions (/Users/bart/Code/content-app/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:3965:11)
    at createComponentInstance (/Users/bart/Code/content-app/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6951:23)
    at renderComponentVNode (/Users/bart/Code/content-app/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:171:22)
    at Module.ssrRenderComponent (/Users/bart/Code/content-app/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:608:12)
    at _sfc_ssrRender (file:///Users/bart/Code/content-app/.nuxt/dist/server/server.mjs:5371:31)
    at renderComponentSubTree (/Users/bart/Code/content-app/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:253:13)
    at renderComponentVNode (/Users/bart/Code/content-app/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:188:16)
    at renderVNode (/Users/bart/Code/content-app/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:295:22)
    at renderVNode (/Users/bart/Code/content-app/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:301:17)
```

**Comment by Atinux** [comment]
It’s not ready yet

**Comment by bart** [comment]
Ah really?? Sorry, I just thought it got released today! If you like I can contribute and help fixing this issue.

**Comment by Atinux** [comment]
The Content component has been renamed ContentDoc :)
