### ISSUE TITLE
Build error after second execution

### ISSUE THREAD

**Issue by bart** [nuxt/content#1157]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v18.1.0`
- Nuxt Version:     `3.0.0-rc.3`
- Package Manager:  `yarn@1.22.18`
- Builder:          `vite`
- User Config:      `modules`
- Runtime Modules:  `@nuxt/content@2.0.0`
- Build Modules:    `-`
------------------------------

### Reproduction

Standard installation of Content V2:

```
npx nuxi init content-app -t content
cd content-app
yarn install
```

Followed by two `build`s
```
yarn build
yarn build
```

### Describe the bug

Second build generates the following error which is located in a vite node chunk file:

```
 ERROR  [unhandledRejection] Cannot read properties of null (reading 'config')                                                                                          02:00:50

  at FSWatcher.reloadOnTsconfigChange (node_modules/vite/dist/node/chunks/dep-59dc6e00.js:6081:16)
  at FSWatcher.emit (node:events:539:35)
  at FSWatcher.emit (node:domain:475:12)
  at FSWatcher.emitWithAll (node_modules/vite/dist/node/chunks/dep-59dc6e00.js:46818:8)
  at FSWatcher._emit (node_modules/vite/dist/node/chunks/dep-59dc6e00.js:46910:8)
  at FSWatcher._remove (node_modules/vite/dist/node/chunks/dep-59dc6e00.js:47173:50)
  at node_modules/vite/dist/node/chunks/dep-59dc6e00.js:47144:50
  at Array.forEach (<anonymous>)
  at FSWatcher._remove (node_modules/vite/dist/node/chunks/dep-59dc6e00.js:47144:27)
  at node_modules/vite/dist/node/chunks/dep-59dc6e00.js:47144:50


 ERROR  [unhandledRejection] Cannot read properties of null (reading 'config')                                                                                          02:00:50

  at FSWatcher.reloadOnTsconfigChange (node_modules/vite/dist/node/chunks/dep-59dc6e00.js:6081:16)
  at FSWatcher.emit (node:events:539:35)
  at FSWatcher.emit (node:domain:475:12)
  at FSWatcher.emitWithAll (node_modules/vite/dist/node/chunks/dep-59dc6e00.js:46818:8)
  at FSWatcher._emit (node_modules/vite/dist/node/chunks/dep-59dc6e00.js:46910:8)
  at FSWatcher._remove (node_modules/vite/dist/node/chunks/dep-59dc6e00.js:47173:50)
  at node_modules/vite/dist/node/chunks/dep-59dc6e00.js:47144:50
  at Array.forEach (<anonymous>)
  at FSWatcher._remove (node_modules/vite/dist/node/chunks/dep-59dc6e00.js:47144:27)
  at FsEventsHandler$1.handleEvent (node_modules/vite/dist/node/chunks/dep-59dc6e00.js:46022:16)
```

**Comment by farnabaz** [comment]
I could not reproduce the exception.  
As stack-trace shows it is likely related to Vite's file watcher  events.

**Comment by bart** [comment]
Hey @farnabaz Thanks for your reply. I can still reproduce by executing the five commands from above. Maybe it is an OS or Node version related issue.

**Comment by farnabaz** [comment]
Did you try it in other environments? like [stackblitz](https://stackblitz.com/fork/github/nuxt/starter/tree/v3-stackblitz)?
If you still have the issue in other environments, please share your reproduction

**Comment by bart** [comment]
Okay, I think I found the real issue: Looks like it is a `yarn` bug in some way. When I execute the build via `npm` multiple times it works well. So I will close this issue for now, thanks!
