### ISSUE TITLE
500 error code when rendering specific md file 

### ISSUE THREAD

**Issue by flik1337** [nuxt/content#1216]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.15.0`
- Nuxt Version:     `3.0.0-rc.3`
- Package Manager:  `npm@8.5.5`
- Builder:          `vite`
- User Config:      `modules`, `css`, `content`, `colorMode`
- Runtime Modules:  `@nuxt/content@2.0.1`, `@nuxtjs/color-mode@3.1.3`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-2kafzy?file=content/index.md

### Describe the bug

I have a list of md files,and the content module works well except this md file.

This md file can be rendered by **markdown-it**,but **cant be rendered** by **content module**.

The log shows "Cannot use 'in' operator to search for 'path' in undefined",and I'm sure it is caused by content module.

I've copied this md file content into the index.md in online sandboxes.

### Logs

```shell
500
Cannot use 'in' operator to search for 'path' in undefined

at Object.resolve (./node_modules/vue-router/dist/vue-router.cjs.js:2875:20)
at ReactiveEffect.eval [as fn] (./node_modules/vue-router/dist/vue-router.cjs.js:2052:45)
at ReactiveEffect.run (./node_modules/@vue/reactivity/dist/reactivity.cjs.js:168:25)
at ComputedRefImpl.get value [as value] (./node_modules/@vue/reactivity/dist/reactivity.cjs.js:1136:39)
at ReactiveEffect.eval [as fn] (./node_modules/vue-router/dist/vue-router.cjs.js:2054:35)
at ReactiveEffect.run (./node_modules/@vue/reactivity/dist/reactivity.cjs.js:168:25)
at ComputedRefImpl.get value [as value] (./node_modules/@vue/reactivity/dist/reactivity.cjs.js:1136:39)
at ReactiveEffect.eval [as fn] (./node_modules/vue-router/dist/vue-router.cjs.js:2079:64)
at ReactiveEffect.run (./node_modules/@vue/reactivity/dist/reactivity.cjs.js:168:25)
at ComputedRefImpl.get value [as value] (./node_modules/@vue/reactivity/dist/reactivity.cjs.js:1136:39)
```

**Comment by flik1337** [comment]
Thanks a lot. @NozomuIkuta 
The error is caused by my irregular writing...
Thanks again!
