### ISSUE TITLE
Using .sort() or .only() with .findSurround() throws 500 error

### ISSUE THREAD

**Issue by LynxTR** [nuxt/content#1360]
### Environment

        "@nuxt/content": "^2.0.1",
        "nuxt": "^3.0.0-rc.5",

  

### Reproduction

https://stackblitz.com/edit/github-f4gbwf?file=README.md

### Describe the bug

Using .sort() or .only() chains, probably not just them but i didn't test all the api, with .findSurround() will result with 500 error.

### Additional context

When you visit reproduction `article-1` and `article-3` links will not open up, unlike `article-2`. You can see the 500 error via manually entering path to stackblitz:  `/articles/random-1`

### Logs

```shell
`500 Internal Server Error (/api/_content/query?_params={%22where%22:[{%22_path%22:%22--REGEX+/^%5C%5C/articles/%22}],%22sort%22:[{%22publishedAt%22:1}],%22only%22:[%22_id%22,%22_path%22,%22inPageHeading%22],%22surround%22:{%22query%22:{%22_path%22:%22/articles/random-1%22}}}&previewToken)`


at onError (./node_modules/ohmyfetch/dist/chunks/fetch.mjs:114:13)
at $fetchRaw2 (./node_modules/ohmyfetch/dist/chunks/fetch.mjs:171:45)
at  ()
```
```

**Comment by farnabaz** [comment]
Thank you @LynxTR for providing a reproduction. This is fixed in the main branch but does not publish yet, you can use the edge channel until the next release. https://stackblitz.com/edit/github-f4gbwf-3j3tlx?file=pages%2Farticles%2F[article].vue

See Docs: https://content.nuxtjs.org/guide/migration/edge-channel

**Comment by LynxTR** [comment]
Oh, i see! Thank you so much.
