### ISSUE TITLE
Two Articles throws error while generating static site.

### ISSUE THREAD

**Issue by rajesh-h** [nuxt/content#141]
Two Articles throws error while generating static site. First Article and another after 100+ generation.
I am really not sure whether is nuxt export error or nuxt content

@nuxt/content: 1.3 
nuxt: 2.13

### Steps to reproduce
Sandbox - https://codesandbox.io/s/github/rajesh-h/cs_content
Github -  https://github.com/rajesh-h/cs_content

run --  yarn generate

### What is Expected?
yarn generate : nuxt  build && nuxt export (Static generation)
should run successfully without any problem

### What is actually happening?
Observe ERROR

```osboxes@osboxes:~/Desktop/webdev/cscom/cs_content$ yarn generate
yarn run v1.22.1
$ nuxt build && nuxt export

 WARN  Experimental @nuxt/telemetry enabled. You can disable this message by explicitly setting telemetry: false or telemetry: true in nuxt.config                              03:19:38

ℹ Parsed 260 files in 0,4 seconds                                                                                                                                 @nuxt/content 03:19:41

 .........
 ERROR  Missing or incomplete config for current environment 'production'!                                                                                        nuxt:firebase 03:22:08

ℹ Generating output directory: dist/                                                                                                                                            03:22:14
ℹ Full static mode activated                                                                                                                                                    03:22:15
ℹ Generating pages                                                                                                                                                              03:22:15
✔ Generated /                                                                                                                                                                   03:22:19
✔ Generated /login                                                                                                                                                              03:22:19

 ERROR   /siqg9sGSDXRzUeLO06fp                                                                                                                                                  03:22:19

TypeError: Cannot read property 'slug' of null
    at a.<anonymous> (1566b3854db4f6ddca50.js:1:26068)
    at a.t._render (/home/osboxes/Desktop/webdev/cscom/cs_content/node_modules/vue/dist/vue.runtime.common.prod.js:6:35273)
    at /home/osboxes/Desktop/webdev/cscom/cs_content/node_modules/vue-server-renderer/build.prod.js:1:70665
    at runNextTicks (internal/process/task_queues.js:62:5)
    at listOnTimeout (internal/timers.js:518:9)
    at processTimers (internal/timers.js:492:7)

✔ Generated /pressure-cooker-eggless-chocolate-nuts-cake-recipe-eggless-baking-without-oven                                                                                     03:22:27
✔ Generated /paneer-tikka-tawa                                                                                                                                                  03:22:27
✔ Generated /grilled-fruit-chaat-recipe-vegetarian-tandoori-recipes-at-home                                                                                                     03:22:27
✔ Generated /besan-ke-ladoo                                                                                                                                                     03:22:27
✔ Generated /wcaf                                                                                                                                                               03:22:27
✔ Generated /n2015d1-mirch-makhani                                                                                                                                              03:22:27
✔ Generated /n2015d3-crispybhindisalad  
............
........
                                                                                                                                                          03:23:26

 ERROR   /cs-garlic-bread-sticks                                                                                                                                                03:23:28

TypeError: Cannot read property 'slug' of null
    at a.<anonymous> (1566b3854db4f6ddca50.js:1:26263)
    at a.t._render (/home/osboxes/Desktop/webdev/cscom/cs_content/node_modules/vue/dist/vue.runtime.common.prod.js:6:35273)
    at /home/osboxes/Desktop/webdev/cscom/cs_content/node_modules/vue-server-renderer/build.prod.js:1:70665
    at runNextTicks (internal/process/task_queues.js:62:5)
    at listOnTimeout (internal/timers.js:518:9)
    at processTimers (internal/timers.js:492:7)

                       
```

**Comment by rajesh-h** [comment]
ok I found the culprit. it was issue where I was using sorround function, and for the first post I had null for next post. and on the last post previous post is null. so these two posts were throwing error.

https://github.com/rajesh-h/cs_content/blob/master/components/blocks/ArticleBlock.vue
this did not through error on dev mode only during export it was throwing error.
```
<div class="bottom-navigation">
      <nuxt-link
        v-if="prevRecipe.slug"
        style="float: left;"
        :to="{
          name: 'slug',
          params: { slug: prevRecipe.slug }
        }"
      >
        {{ prevRecipe.title }}
      </nuxt-link>

      <nuxt-link
        v-if="nextRecipe.slug"
        style="float: right;"
        :to="{
          name: 'slug',
          params: { slug: nextRecipe.slug }
        }"
      >
        {{ nextRecipe.title }}
      </nuxt-link>
    </div>
```

**Comment by rajesh-h** [comment]
Please change label to invalid if possible as its not a Bug
