### ISSUE TITLE
Nitro `service-worker` preset broken on StackBlitz/PNPM

### ISSUE THREAD

**Issue by qin-guan** [nuxt/content#1451]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.8`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `ssr`, `nitro`, `modules`
- Runtime Modules:  `@nuxt/content@2.0.1`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-6kcvvz?file=nuxt.config.ts

### Describe the bug

Using Nuxt Content with the `service-worker` preset on StackBlitz throws the error below during build. The error also occurs when using PNPM locally. Using Yarn resolves the issue. 

### Additional context

Discovered while investigating https://github.com/nuxt/content/issues/1365

### Logs

```shell
WARN  Could not resolve import "parse5/lib/parser/index.js" in /home/projects/github-6kcvvz/node_modules/hast-util-raw/lib/index.js using exports defined in /home/projects/github-6kcvvz/node_modules/parse5/package.json.


 ERROR  Rollup error: Cannot resolve "parse5/lib/parser/index.js" from "/home/projects/github-6kcvvz/node_modules/hast-util-raw/lib/index.js" and externals are not allowed!


 ERROR  Cannot resolve "parse5/lib/parser/index.js" from "/home/projects/github-6kcvvz/node_modules/hast-util-raw/lib/index.js" and externals are not allowed!

  at Object.resolveId (node_modules/nitropack/dist/shared/nitro.8d0213e3.mjs:1073:17)
  at async resolveId (node_modules/rollup/dist/es/shared/rollup.js:21759:26)
  at async ModuleLoader.resolveId (node_modules/rollup/dist/es/shared/rollup.js:22059:19)
  at async Object.resolveId (node_modules/@rollup/plugin-commonjs/dist/es/index.js:589:10)
  at async resolveId (node_modules/rollup/dist/es/shared/rollup.js:21759:26)
  at async ModuleLoader.resolveId (node_modules/rollup/dist/es/shared/rollup.js:22059:19)
  at async eval (node_modules/rollup/dist/es/shared/rollup.js:22342:42)
  at async Promise.all (index 0)
```

**Comment by pi0** [comment]
Hi @qin-guan. I would suggest to track the issue via https://github.com/nuxt/content/issues/1438. There seem multiple incompatibility issues with Content and Worker* targets.

**Comment by qin-guan** [comment]
Ah, I didn’t notice that. The two issues don’t seem too related though 😅 since this seems specific to PNPM/Turbo Package Manager. I cannot reproduce it with Yarn or NPM.
