### ISSUE TITLE
un ordered list in markdown files are not closed propory, 

### ISSUE THREAD

**Issue by cpt-n3mo** [nuxt/content#1546]
### Environment

Nuxt project info:                                                                                                     

------------------------------
- Operating System: `Linux`
- Node Version:     `v18.7.0`
- Nuxt Version:     `3.0.0-rc.11`
- Nitro Version:    `0.5.4`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `modules`
- Runtime Modules:  `@nuxt/content@2.1.1`, `@nuxtjs/tailwindcss@5.3.3`
- Build Modules:    `-`
------------------------------

### Reproduction

see below

### Describe the bug

when one creates a component with multiple slots,
and one passes a list to these slots from a markdown file. 
the second and following slots do not start correctly as the list is not closed.

```
::split
#left
- item1
- item2

#right 
- item3
- item4
::
```

`#right` will cause a error

### Logs

```shell
[nuxt] [request error] [unhandled] [500] Cannot close `componentContainerSection` (15:2-22:1): a different token (`listItem`, 19:1-22:8) is open
  at Object.defaultOnError (./node_modules/mdast-util-from-markdown/lib/index.js:1214:11)  
  at Object.exit (./node_modules/mdast-util-from-markdown/lib/index.js:616:17)  
  at Object.exitContainerSection (./node_modules/remark-mdc/dist/index.mjs:416:8)  
  at compile (./node_modules/mdast-util-from-markdown/lib/index.js:302:40)  
  at fromMarkdown (./node_modules/mdast-util-from-markdown/lib/index.js:120:29)  
  at parser (./node_modules/remark-parse/lib/index.js:15:12)  
  at Function.parse (./node_modules/unified/lib/index.js:273:12)  
  at executor (./node_modules/unified/lib/index.js:393:31)  
  at Function.process (./node_modules/unified/lib/index.js:383:5)  
  at ./.nuxt/dev/index.mjs:1731:12

```
```

**Comment by cpt-n3mo** [comment]
Well its ever worse the following does not work either

```
::split
- item1
- item2

#right 
- item3
- item4
::
```
it seems this also happens with the default slot. anytime a list is used its not closed properly .

**Comment by cpt-n3mo** [comment]
anyone know if there is a version that did not have this prob, so i can revert to that version.? 
im now using a component to make my lists but this is less then ideal,..

**Comment by cpt-n3mo** [comment]
any progress on this ..?

**Comment by ManasMadrecha** [comment]
Is this an issue with only MDC or even with normal syntax, this doesn't work?

**Comment by cpt-n3mo** [comment]
not sure what you mean by normal syntax, but if you mean if you can use lists inside of markdown files then yeh, it just does not work when one wraps it in a component

**Comment by ManasMadrecha** [comment]
By normal syntax, I meant, using HTML syntax for the components, and not the MDC.

**Comment by cpt-n3mo** [comment]
then yeh that works without a problem ..
