### ISSUE TITLE
Sources not working

### ISSUE THREAD

**Issue by stursby** [nuxt/content#1554]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.15.1`
- Nuxt Version:     `3.0.0-rc.11`
- Nitro Version:    `0.5.4`
- Package Manager:  `yarn@1.22.17`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

👉 Report an issue: https://github.com/nuxt/framework/issues/new                                                                                                         12:02:39

👉 Suggest an improvement: https://github.com/nuxt/framework/discussions/new

👉 Read documentation: https://v3.nuxtjs.org

### Reproduction

https://github.com/stursby/nuxt-content-sources-bug

### Describe the bug

Trying to get another sources folder called `snippets` for code snippets. Can't get it working.

I create a fresh Nuxt Content project with `npx nuxi init nuxt-content-source-bug -t content` then added a `snippets` folder in the root dir.

```
├── README.md
├── app.vue
├── content
│   ├── about.md
│   └── index.md
├── nuxt.config.ts
├── package.json
├── pages
│   ├── [...slug].vue
│   └── test.vue
├── snippets
│   └── hello.md
├── tsconfig.json
└── yarn.lock
```

I then tried [multiple config options](https://github.com/stursby/nuxt-content-sources-bug/blob/main/nuxt.config.ts) to load that directory, but getting the following error in iTerm.

```js
import { resolve } from "path";

// https://v3.nuxtjs.org/api/configuration/nuxt.config
export default defineNuxtConfig({
  modules: ["@nuxt/content"],
  content: {
    // Array w/ String doesn't work
    // sources: ["snippets"],

    // ...doesn't work either
    sources: [
      "snippets",
      {
        name: "snippets",
        driver: "fs",
        base: resolve(__dirname, "snippets"), // Path for source directory
      },
    ],
  },
});
```

For example, I [created a test page](https://github.com/stursby/nuxt-content-sources-bug/blob/main/pages/test.vue) and tried to pull in that snippet.

```bash
Nuxi 3.0.0-rc.11                                                                                                                                                         12:04:59
Nuxt 3.0.0-rc.11 with Nitro 0.5.4                                                                                                                                        12:04:59
                                                                                                                                                                         12:05:01
  > Local:    http://localhost:3000/
  > Network:  http://10.0.0.196:3000/
  > Network:  http://[2601:445:500:1200:610c:38e7:e249:e1e8]:3000/
  > Network:  http://[2601:445:500:1200:8da:1a0f:e880:45e4]:3000/
  > Network:  http://[2601:445:500:1200::ab06]:3000/

ℹ Cleaning up generated nuxt files and caches...                                                                                                                         12:05:01

 ERROR  Cannot start nuxt:  Cannot find package 'undefined' imported from /Users/hield/Sites/__SCRAP__/nuxt-content-source-bug/node_modules/nitropack/dist/shared/nitro.9c828268.mjs

  at new NodeError (node:internal/errors:372:5)
  at packageResolve (node:internal/modules/esm/resolve:954:9)
  at moduleResolve (node:internal/modules/esm/resolve:1003:20)
  at defaultResolve (node:internal/modules/esm/resolve:1218:11)
  at ESMLoader.resolve (node:internal/modules/esm/loader:580:30)
  at ESMLoader.getModuleJob (node:internal/modules/esm/loader:294:18)
  at ESMLoader.import (node:internal/modules/esm/loader:380:22)
  at importModuleDynamically (node:internal/modules/esm/translators:106:35)
  at importModuleDynamicallyCallback (node:internal/process/esm_loader:35:14)
  at createStorage (node_modules/nitropack/dist/shared/nitro.9c828268.mjs:1189:69)
```

**Comment by ManasMadrecha** [comment]
Add a `prefix` too and then try.

**Comment by stursby** [comment]
@ManasMadrecha still the same error...

updated in my `nuxt.config.ts`:

```ts
import { resolve } from "path";

// https://v3.nuxtjs.org/api/configuration/nuxt.config
export default defineNuxtConfig({
  modules: ["@nuxt/content"],
  content: {
    // Array w/ String doesn't work
    // sources: ["snippets"],

    // ...doesn't work either
    sources: [
      "snippets",
      {
        name: "snippets",
        driver: "fs",
        prefix: "/snippets",
        base: resolve(__dirname, "snippets"), // Path for source directory
      },
    ],
  },
});
```

And get this in iTerm

```
➜  nuxt-content-source-bug git:(main) npm run dev

> dev
> nuxt dev
Nuxi 3.0.0-rc.11                                                                              14:30:13
Nuxt 3.0.0-rc.11 with Nitro 0.5.4                                                             14:30:14
                                                                                              14:30:21
  > Local:    http://localhost:3000/
  > Network:  http://10.0.0.196:3000/
  > Network:  http://[2601:445:500:1200:610c:38e7:e249:e1e8]:3000/
  > Network:  http://[2601:445:500:1200:8da:1a0f:e880:45e4]:3000/
  > Network:  http://[2601:445:500:1200::ab06]:3000/
  > Network:  http://[2601:445:500:1200:a8aa:5fd1:c0a:af08]:3000/


 ERROR  Cannot start nuxt:  Cannot find package 'undefined' imported from /Users/hield/Sites/__SCRAP__/nuxt-content-source-bug/node_modules/nitropack/dist/shared/nitro.9c828268.mjs

  at new NodeError (node:internal/errors:372:5)
  at packageResolve (node:internal/modules/esm/resolve:954:9)
  at moduleResolve (node:internal/modules/esm/resolve:1003:20)
  at defaultResolve (node:internal/modules/esm/resolve:1218:11)
  at ESMLoader.resolve (node:internal/modules/esm/loader:580:30)
  at ESMLoader.getModuleJob (node:internal/modules/esm/loader:294:18)
  at ESMLoader.import (node:internal/modules/esm/loader:380:22)
  at importModuleDynamically (node:internal/modules/esm/translators:106:35)
  at importModuleDynamicallyCallback (node:internal/process/esm_loader:35:14)
  at createStorage (node_modules/nitropack/dist/shared/nitro.9c828268.mjs:1189:69)
  at createNitro (node_modules/nitropack/dist/shared/nitro.9c828268.mjs:2357:25)
  at async initNitro (node_modules/nuxt/dist/index.mjs:1402:17)
  at async initNuxt (node_modules/nuxt/dist/index.mjs:1612:3)
  at async load (node_modules/nuxi/dist/chunks/dev.mjs:6778:9)
  at async Object.invoke (node_modules/nuxi/dist/chunks/dev.mjs:6828:5)
  at async _main (node_modules/nuxi/dist/cli.mjs:50:20)
``

**Comment by ROBJkE** [comment]
@stursby  i got exactly same error. i removed the string from array and that worked for me.
try this:

``` js
import { resolve } from "path";

// https://v3.nuxtjs.org/api/configuration/nuxt.config
export default defineNuxtConfig({
  modules: ["@nuxt/content"],
  content: {
    sources: [
      {
        name: "snippets",
        driver: "fs",
        prefix: "/snippets",
        base: resolve(__dirname, "snippets"), // Path for source directory
      },
    ],
  },
});
```

**Comment by stursby** [comment]
@ROBJkE Nice! That worked!!

Wonder if the Nuxt Content Docs just need to get updated... since [they currently show it](https://content.nuxtjs.org/api/configuration#sources) like I had it (when it was breaking...)

<img width="358" alt="image" src="https://user-images.githubusercontent.com/527849/192598093-a4c4fd32-7bf5-4c75-bf3a-30deebf840ba.png">

And then I just had to update the prefix in the `:path` prop of `<ContentDoc/>`

So it becomes:

```vue
<ContentDoc path="snippets/hello" />
```

Thanks for solving it!!

**Comment by ManasMadrecha** [comment]
@stursby Even single-line string works. 

In your case it didn't work because you were writing the same "snippets" in both the string as well as object syntax, so the Module was unable to figure out which folder to be used for "snippets". With only `"snippets"` syntax, the Module will keep its prefix as `/`, and then in the Object syntax you were adding the prefix as `/snippets`; hence the clash.

On the Website, the docs have properly shown the example of using two totally different folders "content" and "content-fa"; so no clash there.

**Comment by ROBJkE** [comment]
@ManasMadrecha incorrect. Even with a unique single string that error occurs.

**Comment by ManasMadrecha** [comment]
@ROBJkE yes, thanks, created a new issue for that.
