### ISSUE TITLE
"Cannot read properties of undefined (reading 'content')" after upgrading to nuxt3-rc14

### ISSUE THREAD

**Issue by ahoiroman** [nuxt/content#1687]
### Environment

```
- Operating System: `Darwin`
- Node Version:     `v18.11.0`
- Nuxt Version:     `3.0.0-rc.14`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@8.19.2`
- Builder:          `vite`
- User Config:      `build`, `modules`, `publicRuntimeConfig`, `privateRuntimeConfig`, `globalName`, `app`, `i18n`, `http`, `proxy`, `auth`, `tailwindcss`, `googleFonts`
- Runtime Modules:  `@nuxtjs-alt/auth@2.0.16`, `@nuxtjs-alt/http@1.4.6`, `@nuxtjs-alt/proxy@1.3.8`, `@nuxt/content@2.2.2`, `@nuxtjs/tailwindcss@6.1.3`, `@nuxtjs/google-fonts@3.0.0-1`, `@pinia/nuxt@0.4.3`, `@nuxtjs/i18n@8.0.0-beta.4`, `@nuxt/image-edge@1.0.0-27809804.194d2d6`
- Build Modules:    `-`
```

### Reproduction

After upgrading to nuxt3-rc14, Nuxt-content prevents the start with the message I posted below. Worked fine with rc13. 

### Describe the bug

```
Cannot start nuxt:  Cannot read properties of undefined (reading 'content')

  at setup (node_modules/@nuxt/content/dist/module.mjs:431:88)
  at async normalizedModule (node_modules/@nuxt/kit/dist/index.mjs:167:5)
  at async installModule (node_modules/@nuxt/kit/dist/index.mjs:416:3)
  at async initNuxt (node_modules/nuxt/dist/index.mjs:1827:7)
  at async load (node_modules/nuxi/dist/chunks/dev.mjs:6779:9)
  at async Object.invoke (node_modules/nuxi/dist/chunks/dev.mjs:6840:5)
  at async _main (node_modules/nuxi/dist/cli.mjs:50:20)
```

**Comment by Atinux** [comment]
Could you upgrade to 3.0 and try again?

**Comment by ahoiroman** [comment]
Hi there,

that worked. Thanks!

**Comment by otomad** [comment]
Hello, how did you do this?

I've already `Nuxt Version: 3.0.0-rc.14` and `@nuxt/content: 2.3.0`, but still get this error.

I tried to `npx nuxi upgrade`, and keep getting this error `Cannot read properties of undefined (reading 'content')` at runtime.
