### ISSUE TITLE
failed to find "useUnwrap" imported from "#imports"

### ISSUE THREAD

**Issue by Flowko** [nuxt/content#1688]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.14`
- Nitro Version:    `1.0.0`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `nitro`, `hooks`, `modules`, `components`, `typescript`, `css`, `runtimeConfig`, `app`, `content`, `googleFonts`, `image`, `umami`
- Runtime Modules:  `@nuxt/content@2.2.2`, `@nuxtjs/tailwindcss@6.1.3`, `@nuxtjs/google-fonts@3.0.0-1`, `@nuxt/image-edge@1.0.0-27809804.194d2d6`, `@pinia/nuxt@0.4.3`, `nuxt-icon@0.1.7`, `nuxt-swiper@0.1.6`, `@formkit/nuxt@1.0.0-beta.12`, `nuxt-umami@1.1.1`
- Build Modules:    `-`

### Reproduction

After upgrading to nuxt3-rc14, pages that have nuxt-content components show the message below. Worked fine with rc13.

### Describe the bug

[plugin:nuxt:imports-transform] [unimport] failed to find "useUnwrap" imported from "#imports"

[Project-Dir]/node_modules/@nuxt/content/dist/runtime/components/ContentSlot.vue

  at file:///[Project-Dir]/node_modules/unimport/dist/shared/unimport.d5d80c71.mjs:782:17
    at Array.forEach (<anonymous>)
    at file:///[Project-Dir]/node_modules/unimport/dist/shared/unimport.d5d80c71.mjs:779:44
    at Array.forEach (<anonymous>)
    at detectImports (file:///[Project-Dir]/node_modules/unimport/dist/shared/unimport.d5d80c71.mjs:777:20)
    at async injectImports (file:///[Project-Dir]/node_modules/unimport/dist/shared/unimport.d5d80c71.mjs:804:44)
    at async TransformContext.transform (file:///[Project-Dir]/node_modules/nuxt/dist/index.mjs:1107:21)
    at async Object.transform (file:///[Project-Dir]/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:40228:30)
    at async loadAndTransform (file:///[Project-Dir]/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:36615:29

**Comment by farnabaz** [comment]
Could you try to clean install your project by removing `yarn.lock` and `node_modules`?

**Comment by Flowko** [comment]
yeah that seems to fix it, i only deleted node_modules at my first try, thanks
