### ISSUE TITLE
ReferenceError: url is not defined

### ISSUE THREAD

**Issue by Barbapapazes** [nuxt/content#1851]
### Environment

Nuxi 3.1.0                                                                                                                                        08:40:31
                                                                                                                                                  08:40:32
RootDir: C:/Users/esoubiran/dev/barbapapazes/le-classement.fr                                                                                     08:40:32
Nuxt project info:                                                                                                                                08:40:32

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v18.12.1`
- Nuxt Version:     `3.1.0`
- Nitro Version:    `2.1.0`
- Package Manager:  `yarn@3.3.1`
- Builder:          `vite`
- User Config:      `extends`, `modules`, `runtimeConfig`, `content`, `app`, `nitro`
- Runtime Modules:  `@vueuse/nuxt@9.11.1`, `@nuxtjs/tailwindcss@6.3.0`, `@nuxtjs/fontaine@0.2.4`, `@nuxt/content@2.4.0`, `nuxt-icon@0.2.10`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-sospeq-jtqvnp?file=content/about.md

### Describe the bug

URL can't be founded.

### Logs

```
[nitro] [dev] [unhandledRejection] ReferenceError: url is not defined                                                                             08:39:00
    at refreshHead (C:\Users\esoubiran\dev\barbapapazes\le-classement.fr\node_modules\@nuxt\content\dist\runtime\composables\head.mjs:72:138)
    at callWithErrorHandling (C:\Users\esoubiran\dev\barbapapazes\le-classement.fr\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:157:22)
    at callWithAsyncErrorHandling (C:\Users\esoubiran\dev\barbapapazes\le-classement.fr\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:166:21)
    at doWatch (C:\Users\esoubiran\dev\barbapapazes\le-classement.fr\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:1752:13)
    at Module.watch (C:\Users\esoubiran\dev\barbapapazes\le-classement.fr\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:1663:12)
    at Module.useContentHead (C:\Users\esoubiran\dev\barbapapazes\le-classement.fr\node_modules\@nuxt\content\dist\runtime\composables\head.mjs:107:25)
    at setup (C:\Users\esoubiran\dev\barbapapazes\le-classement.fr\node_modules\@nuxt\content\dist\runtime\pages\document-driven.vue:26:27)
    at _sfc_main.setup (C:\Users\esoubiran\dev\barbapapazes\le-classement.fr\node_modules\@nuxt\content\dist\runtime\pages\document-driven.vue:93:23)
    at callWithErrorHandling (C:\Users\esoubiran\dev\barbapapazes\le-classement.fr\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:157:22)
    at setupStatefulComponent (C:\Users\esoubiran\dev\barbapapazes\le-classement.fr\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:7176:29)
```

_No response_

**Comment by Atinux** [comment]
I don't have any problem in the reproduction @Barbapapazes

**Comment by Barbapapazes** [comment]
Ok, I know why ! Wait a little and change navigate through pages. The error will appear in the console.

**Comment by Barbapapazes** [comment]
![image.png](https://volta.s3.fr-par.scw.cloud/image_b5c15c6bce.png)

Some time passed between the hmr ready and the error.

**Comment by tex0l** [comment]
I have the same issue that appeared in my generate logs, it comes from this line: https://github.com/nuxt/content/blob/9923502d9838e0f45e4136d8df6eb8477745ec47/src/runtime/composables/head.ts#L91

**Comment by tex0l** [comment]
I think this is a regression introduced in https://github.com/nuxt/content/pull/1769, there is a ts-ignore which prevents TS from warning, but `url` is just not defined in this scope.

**Comment by farnabaz** [comment]
This should be fixed in edge channel, we will release a hotfix today `v2.4.1`

**Comment by tex0l** [comment]
I can confirm the edge channel works with the latest fix.
