### ISSUE TITLE
Documents are all null in production

### ISSUE THREAD

**Issue by ydnar** [nuxt/content#1900]
### Environment

- Operating System: `Darwin`
- Node Version:     `v19.5.0`
- Nuxt Version:     `3.2.0`
- Nitro Version:    `2.2.1`
- Package Manager:  `pnpm@7.26.3`
- Builder:          `vite`
- User Config:      `telemetry`, `modules`, `vite`, `runtimeConfig`, `css`, `app`, `content`, `i18n`
- Runtime Modules:  `@nuxtjs/i18n@8.0.0-beta.9`, `@nuxt/content@2.4.3`
- Build Modules:    `-`

### Reproduction

https://beta.domainr.com/_/api/content/query/all.json

### Describe the bug

`@nuxt/content` works correctly in dev, with `nuxt preview`, and locally. When deployed to Heroku, all docs are null, which throws an unhandled error when rendering the content. The cache.json file is essentially `[null, null, null, null...]`.

It has the correct number of docs, and the build process reports generating all the relevant js/mjs files for the Markdown content files.

I can’t determine if the issue is in `nuxt`, `@nuxt/content`, `nitro`, or `unstorage`.

### Additional context

This is the last thing blocking us from migrating from Nuxt 2.x to 3.x!

### Logs

```shell
method="GET" path="/_/api/content/query/4iQohvzBYE.1676062776413.json?_params={%22first%22:true,%22where%22:[{%22_path%22:%22/about%22}],%22sort%22:[{%22_file%22:1,%22$numeric%22:true}]}" request_id="8efae271-502a-4c09-8fd6-b75d1279cd60" fwd="75.26.17.220" useragent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.3 Safari/605.1.15"
[nuxt] [request error] [unhandled] [500] Cannot read properties of undefined (reading '_path')
at ./.output/server/chunks/nitro/node-server.mjs:4859:16
at Array.reduce (<anonymous>)
at getContentIndex (./.output/server/chunks/nitro/node-server.mjs:4858:25)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async getIndexedContentsList (./.output/server/chunks/nitro/node-server.mjs:4875:19)
at async ./.output/server/chunks/nitro/node-server.mjs:2410:18
at async ./.output/server/chunks/nitro/node-server.mjs:5114:21
at async Object.handler (./.output/server/node_modules/h3/dist/index.mjs:990:19)
at async Server.toNodeHandle (./.output/server/node_modules/h3/dist/index.mjs:1065:7)
```

**Comment by ydnar** [comment]
I think I’ve traced the issue to `getContent`, returning `null` (or `undefined`) for all docs somewhere in the function:

https://github.com/nuxt/content/blob/main/src/runtime/server/storage.ts#L112

**Comment by ydnar** [comment]
Turns out the issue was on our end. We had Nitro middleware that redirected the prerender request to https, which failed.

This may point to an another issue—prerendering silently swallows errors rather than fail the build. Seems like that might be preferable?
