### ISSUE TITLE
Material Themes not Loading Shiki

### ISSUE THREAD

**Issue by dbzx10299** [nuxt/content#1936]
### Environment

```
------------------------------
- Operating System: `Darwin`
- Node Version:     `v19.4.0`
- Nuxt Version:     `3.2.2`
- Nitro Version:    `2.2.3`
- Package Manager:  `npm@9.2.0`
- Builder:          `vite`
- User Config:      `css`, `modules`, `content`, `pinia`
- Runtime Modules:  `@nuxt/content@2.4.3`, `@pinia/nuxt@0.4.7`, `@vueuse/nuxt@9.13.0`
- Build Modules:    `-`
------------------------------
```

### Reproduction

```js
export default defineNuxtConfig({
  modules: ['@nuxt/content'],
  content: {
    highlight: {
      theme: 'material-theme-darker'
    }
  }
})
```

### Describe the bug

Any of the material themes used with shiki will not load, there is an error that is thrown in the console. All other shiki themes are working except material themes.
```
material-theme-darker
material-theme-lighter
...
```

### Logs

```shell
[nuxt] [request error] [unhandled] [500] Unknown asset: themes/material-theme-palenight.json                                                                       17:15:37
  at globalThis.__shiki_fetch__ (./node_modules/shiki-es/dist/shiki.node.mjs:188:11)  
  at _fetchAssets (./node_modules/shiki-es/dist/shiki.mjs:1879:64)  
  at _fetchJSONAssets (./node_modules/shiki-es/dist/shiki.mjs:1884:32)  
  at fetchTheme (./node_modules/shiki-es/dist/shiki.mjs:1893:21)  
  at Registry.loadTheme (./node_modules/shiki-es/dist/shiki.mjs:2262:45)  
  at ./node_modules/shiki-es/dist/shiki.mjs:2274:57  
  at Array.map (<anonymous>)  
  at Registry.loadThemes (./node_modules/shiki-es/dist/shiki.mjs:2274:37)  
  at getHighlighter (./node_modules/shiki-es/dist/shiki.mjs:2358:34)  
  at getShikiHighlighter (./.nuxt/dev/index.mjs:2883:17)
```

**Comment by nobkd** [comment]
@dbzx10299

Does this still happen for you? Because I can't reproduce it anymore.

**Comment by dbzx10299** [comment]
No, not anymore

**Comment by nobkd** [comment]
That's good to hear 😃

**Comment by hecktarzuli** [comment]
I just nuked my yarn.lock file, and upgraded to Nuxt 3.6.5 / content 2.7.2.  I'm now getting this error when trying to build.
