### ISSUE TITLE
unable to use Content v1 with nuxt 2 and nuxt-bridge

### ISSUE THREAD

**Issue by existe-deja** [nuxt/content#1937]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.19.0`
- Nuxt Version:     `2.16.1`
- Nitro Version:    `1.0.0`
- Package Manager:  `yarn@1.22.19`
- Builder:          `webpack`
- User Config:      `target`, `components`, `runtimeConfig`, `app`, `css`, `loading`, `plugins`, `devServerHandlers`, `modules`, `build`, `router`, `twicpics`, `i18n`, `toast`, `sentry`, `content`, `serverHandlers`, `devServer`, `typescript`, `bridge`, `buildModules`
- Runtime Modules:  `@nuxtjs/axios@5.13.6`, `@nuxtjs/toast@3.3.1`,  `@nuxtjs/i18n@7.3.1`, `@nuxtjs/sentry@6.0.3`, `@twicpics/components/nuxt2@0.15.1`, `@nuxt/content@1.15.1`
- Build Modules:    `()`, `@nuxt/bridge@3.0.0-27928371.c30fa0f`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-xg6owu?file=nuxt.config.js

You can switch config and use `dev-old` npm script to run it.

### Describe the bug

Nuxt Content v1 doesn't support nuxt-bridge syntax even with a working nuxt2 stack. It makes impossible to use nuxt-bridge at all because this dependency is already used in a production project.

### Logs

```shell
stack trace

[nuxt] [request error] inject('content', value) has no value provided                                                                                                    12:31:53
  at inject (./.nuxt/dist/server/server.js:16678:13)  
  at module.exports../.nuxt/content/plugin.server.js.__webpack_exports__.default (./.nuxt/dist/server/server.js:16392:3)  
  at createApp (./.nuxt/dist/server/server.js:16738:93)  
  at async module.exports../.nuxt/server.js.__webpack_exports__.default (./.nuxt/dist/server/server.js:32206:7)  
  at async Object.renderToString (./node_modules/vue-bundle-renderer/dist/runtime.mjs:172:19)  
  at async ./.nuxt/dev/index.mjs:1123:21  
  at async ./.nuxt/dev/index.mjs:108:22  
  at async Object.handler (./node_modules/h3/dist/index.mjs:1196:19)  
  at async Server.toNodeHandle (./node_modules/h3/dist/index.mjs:1271:7)
[nitro] Error while generating error response FetchError:  (500  (/__nuxt_error?url=/&statusCode=500&statusMessage&message=inject('content',+value)+has+no+value+provided&description=%3Cpre%3E%3Cspan+class=%22stack%22%3Eat+inject+(./.nuxt/dist/server/server.js:16678:13)%3C/span%3E%0A%3Cspan+class=%22stack%22%3Eat+module.exports../.nuxt/content/plugin.server.js.__webpack_exports__.default+(./.nuxt/dist/server/server.js:16392:3)%3C/span%3E%0A%3Cspan+class=%22stack%22%3Eat+createApp+(./.nuxt/dist/server/server.js:16738:93)%3C/span%3E%0A%3Cspan+class=%22stack%22%3Eat+async+module.exports../.nuxt/server.js.__webpack_exports__.default+(./.nuxt/dist/server/server.js:32206:7)%3C/span%3E%0A%3Cspan+class=%22stack+internal%22%3Eat+async+Object.renderToString+(./node_modules/vue-bundle-renderer/dist/runtime.mjs:172:19)%3C/span%3E%0A%3Cspan+class=%22stack%22%3Eat+async+./.nuxt/dev/index.mjs:1123:21%3C/span%3E%0A%3Cspan+class=%22stack%22%3Eat+async+./.nuxt/dev/index.mjs:108:22%3C/span%3E%0A%3Cspan+class=%22stack+internal%22%3Eat+async+Object.handler+(./node_modules/h3/dist/index.mjs:1196:19)%3C/span%3E%0A%3Cspan+class=%22stack+internal%22%3Eat+async+Server.toNodeHandle+(./node_modules/h3/dist/index.mjs:1271:7)%3C/span%3E%3C/pre%3E))
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.errorhandler [as onError] (file:///home/existe_deja/projects/rental-front-web/.nuxt/dev/index.mjs:424:16)
    at async Server.toNodeHandle (file:///home/existe_deja/projects/rental-front-web/node_modules/h3/dist/index.mjs:1278:9)
```
```

**Comment by minagu111** [comment]
same problem, i follow up
