### ISSUE TITLE
the consola dependency of @nuxt/content started to report errors.

### ISSUE THREAD

**Issue by tye-js** [nuxt/content#2013]
### Environment

Nuxt project info: (copied to clipboard)                                                                                                                               00:40:59

------------------------------
- Operating System: Darwin
- Node Version:     v16.16.0
- Nuxt Version:     3.4.1
- Nitro Version:    2.3.3
- Package Manager:  pnpm@8.2.0
- Builder:          vite
- User Config:      css, ssr, vite, modules, nitro, sitemap, tailwindcss, robots, image, pinia, app
- Runtime Modules:  @nuxtjs/tailwindcss@6.6.5, @pinia/nuxt@0.4.7, @element-plus/nuxt@1.0.4, @nuxt/content@2.5.2, @nuxt/image-edge@1.0.0-28020728.5df24eb, nuxt-simple-sitemap@2.4.11, @nuxtjs/robots@3.0.0
- Build Modules:    -
------------------------------

### Reproduction

The developed project is local.

### Describe the bug

After I upgraded to nuxt3.4.1 and started my project, I found that the consola dependency of @nuxt/content started to report errors.When I removed @nuxt/content, the project was able to start successfully.

### Additional context

in my pnpm-lock.yaml:
 /@nuxt/content@2.5.2:
    resolution: {integrity: sha512-bSO4g2aNk7AT5abAIJtHLTN+FZFYMvwP6MH9oP6XAo/SsIowvFq7g38in3jK/OMDR+dZq3Nt1z8GrMDGipzsfQ==}
    dependencies:
      '@nuxt/kit': 3.2.3
      consola: 2.15.3
      defu: 6.1.2
      destr: 1.2.2
...

### Logs

```shell
[nuxt] [request error] [unhandled] [500] Named export 'consola' not found. The requested module 'consola' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'consola';
const { consola } = pkg;

  at ModuleJob._instantiate (node:internal/modules/esm/module_job:128:21)  
  at async ModuleJob.run (node:internal/modules/esm/module_job:194:5)  
  at async Promise.all (index 0)  
  at async ESMLoader.import (node:internal/modules/esm/loader:385:24)  
  at async ./.nuxt/dev/index.mjs:4463:24  
  at async ./.nuxt/dev/index.mjs:4542:64  
  at async ./.nuxt/dev/index.mjs:437:22  
  at async Object.handler (./node_modules/.pnpm/h3@1.6.4/node_modules/h3/dist/index.mjs:1247:19)  
  at async Server.toNodeHandle (./node_modules/.pnpm/h3@1.6.4/node_modules/h3/dist/index.mjs:1322:7)
```

**Comment by zeferinix** [comment]
Encountering this as well from a fresh Nuxt 3.4 project to try out `@nuxt/content`.

![image](https://user-images.githubusercontent.com/6721822/232391723-48c1d784-2432-4e6f-ad44-a9a86083a11f.png)

Exact same deps as above except on Node v18.15.0.

**Comment by farnabaz** [comment]
This should be fixed in [edge channel](https://content.nuxtjs.org/guide/migration/edge-channel) and soon will be released in v2.6

**Comment by farnabaz** [comment]
This one also will fix in next release, It's just a warning for deprecated syntax. It has no affect on module behaviour at the time.
For now you can ignore this one.

**Comment by prisme** [comment]
I'm running into a similar issue, which is either crashing my project's local dev environment, or Vercel deployments

## Environment

- Operating System: `Darwin`
- Node Version:     `v18.12.1`
- Nuxt Version:     `3.3.2`
- Nitro Version:    `2.3.2`
- Package Manager:  `pnpm@7.30.3`
- Builder:          `vite`
- User Config:      `modules`, `css`, `apollo`, `googleFonts`
- Runtime Modules:  `@nuxtjs/apollo@5.0.0-alpha.6`, `@nuxtjs/google-fonts@3.0.0`, `@nuxt/content@2.6.0`
- Build Modules:    `-`

## Reproduction

after installing nuxt-content 2.6.0 and adding it to nuxt.config modules I got this error, 
when running local dev and when building on vercel 

![image](https://user-images.githubusercontent.com/415480/234122955-5dea797c-cfa7-4f3c-b82b-f5fcae4087e6.png)

installing unenv 1.4.1 fixed the problem on local dev, but raises an error 500 on Vercel

```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/var/task/node_modules/unstorage/drivers/overlay.mjs' imported from /var/task/index.mjs
    at new NodeError (node:internal/errors:400:5)
    at finalizeResolution (node:internal/modules/esm/resolve:331:11)
    at moduleResolve (node:internal/modules/esm/resolve:994:10)
    at moduleResolveWithNodePath (node:internal/modules/esm/resolve:938:12)
    at defaultResolve (node:internal/modules/esm/resolve:1202:79)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:842:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40)
    at link (node:internal/modules/esm/module_job:76:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
RequestId: c058bdfa-9db7-4ca6-a5d1-22b5ead2f769 Error: Runtime exited with error: exit status 1
Runtime.ExitError

```

## Describe the bug

can't get my project to build on Vercel after adding nuxt-content

## Additional context

here's my pnpm-lock.yaml diff

![image](https://user-images.githubusercontent.com/415480/234121063-5779f834-3e46-46e9-a37f-d5f58e6e745a.png)

**Comment by candidappbr** [comment]
Steps:
```
# clear all
yarn remove @nuxt/content
rimraf .nuxt
rimraf node_modules

# install again
yarn add @nuxt/content #   <- version 2.7.0
```

![image](https://github.com/nuxt/content/assets/98469655/f71e9301-ff58-4627-bf99-03ab26c862f6)

Error in version 2.7

Downgraded to Version 2.6 and works
