### ISSUE TITLE
Broken setup

### ISSUE THREAD

**Issue by adamalfredsson** [nuxt/content#2058]
### Environment

```
npx nuxi info                                                                                                                                                             11:30:48
Need to install the following packages:
  nuxi
Ok to proceed? (y) y
Nuxt CLI v3.0.0-27238235.a1bcc53                                                                                                                                                            11:32:38
RootDir: /Users/Adam/Projects/djurens-ratt                                                                                                                                                  11:32:38
Nuxt project info:                                                                                                                                                                          11:32:38

------------------------------
- Operating System: `Darwin`
- Node Version:     `v18.15.0`
- Nuxt Version:     `-`
- Package Manager:  `npm`
- Bundler:          `Webpack`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------


 ERROR  Cannot read properties of null (reading 'startsWith')                                                                                                                               11:32:38

  at Object.invoke (/Users/Adam/.npm/_npx/a95e0f536cf9a537/node_modules/nuxi-edge/dist/chunks/info.mjs:2221:41)
  at async _main (/Users/Adam/.npm/_npx/a95e0f536cf9a537/node_modules/nuxi-edge/dist/chunks/index.mjs:417:7)
```

### Reproduction

`npx nuxi init content-app -t content`

### Describe the bug

```
npx nuxi init content-app -t content                                                                                                                                      11:30:42
Need to install the following packages:
  nuxi
Ok to proceed? (y) y
Nuxt CLI v3.0.0-27238235.a1bcc53                                                                                                                                                            11:30:48

 ERROR  could not parse content                                                                                                                                                             11:30:48

  at parse (/Users/Adam/.npm/_npx/a95e0f536cf9a537/node_modules/nuxi-edge/dist/chunks/init.mjs:14362:9)
  at new Degit (/Users/Adam/.npm/_npx/a95e0f536cf9a537/node_modules/nuxi-edge/dist/chunks/init.mjs:14065:15)
  at degit (/Users/Adam/.npm/_npx/a95e0f536cf9a537/node_modules/nuxi-edge/dist/chunks/init.mjs:14052:9)
  at Object.invoke (/Users/Adam/.npm/_npx/a95e0f536cf9a537/node_modules/nuxi-edge/dist/chunks/init.mjs:14676:19)
  at _main (/Users/Adam/.npm/_npx/a95e0f536cf9a537/node_modules/nuxi-edge/dist/chunks/index.mjs:417:17)
```

**Comment by adamalfredsson** [comment]
`npx nuxi@latest init content-app -t content` works, perhaps this could be the recommended setup?

**Comment by Atinux** [comment]
Actually if you already have `nuxt` installed the `npx nuxi` will used the installed Nuxt version so the command is correct
