### ISSUE TITLE
Allow passing components to the content renderer

### ISSUE THREAD

**Issue by helltraitor** [nuxt/content#2148]
### Real usage
We have prose components which slightly different: `h1` - `h6`
We can make template component, that will accept original id and would have default slot, but with additional props (e.g. level and styling for `h*`).

#### Considered usage
```ts
const templateHeading = ({ level: number, classes: string } = {}) => 
  defineComponent({
    // USE TEMPLATE COMPONENT HERE
  })

const MarkdownComponents = {
  h1: templateHeading({ level: 1, classes: 'text-3xl' }),
  h2: templateHeading({ level: 2, classes: 'text-xl' }),
  // REST
}
```

### Current workaround
Register components for Vue instance which makes them global (that maybe not desired)

```ts
useNuxtApp().vueApp.component('CustomProseH1', templateHeading({ level: 1, classes: 'text-3xl' })
useNuxtApp().vueApp.component('CustomProseH2', templateHeading({ level: 2, classes: 'text-xl' })
// REST

const MarkdownComponents = {
  h1: 'CustomProseH1,
  h2: 'CustomProseH2'
  // REST
}
```

Please note, that this is doesn't matter use you cycles or not, the thing is in global accessing for created components.
Probably you could add some magic prefix, hash - whatever, but as for me, anonymous components are more desirable.

### Additional
I don't ask for changing default behavior, just ask for ability to use components alongside with strings if this is possible (probably, yes)

**Comment by Barbapapazes** [comment]
Hello,

Could you explain more you current usage and why you want to do it?

**Comment by helltraitor** [comment]
> Hello,
> 
> Could you explain more you current usage and why you want to do it?

Current usage is just pass strings and use global `components/content`.

The thing is: they boilerplate too much. The 6 component with minor changes can be freely replaced by one template component. I can do this even now (via registering created components in Vue instance).

But I can't see any reason to not to extend current functional.

Hope, now you understand why I need this

**Comment by farnabaz** [comment]
You can expect this feature in next release 🙂

**Comment by helltraitor** [comment]
@farnabaz can you reopen this issue if still planned?

**Comment by farnabaz** [comment]
@helltraitor This feature is available in Content v3. You can upgrade to version 3 (which is in alpha and will release soon).

```vue
<script setup>
import MyCustomACompoenent from '/path/to/component'
</script>
<template>
<ContentRenderer :components="{ a: MyCustomACompoenent }" />
</template>
```

**Comment by chrisjansky** [comment]
> [@helltraitor](https://github.com/helltraitor) This feature is available in Content v3. You can upgrade to version 3 (which is in alpha and will release soon).

@farnabaz Hi, I am having trouble making it work – here’s a minimal reproduction: https://stackblitz.com/edit/nuxt-starter-jtjndwmm?file=app.vue

```
 WARN  [Vue warn]: Failed to resolve component: Foo
```

@Barbapapazes I am not OP, but my use case is: I’d like to reuse shadcn-vue components inside markdown files. I need to explicitly import them into <ContentRenderer>.

I tried declaring some of them as global by placing them into `components/global` via nuxt.config.ts:

```ts
components: {
   { path: "~/components/global", pathPrefix: false, global: true }, // ? Make shadcn-vue available in .md files
}
```

But turns out this breaks build process in Cloudflare Pages: `Error: Failed to publish your Function. Got error: Uncaught ReferenceError: require is not defined
  at chunks/nitro/nitro.mjs:1:520716`

So I need to import the components explicitly without moving them into the global scope.

**Comment by chrisjansky** [comment]
#3127 does fix explicit imports for me, i.e. delete the global settings from `nuxt.config.ts` like so

~~`{ path: "~/components/global", pathPrefix: false, global: true }`~~

and import the needed components one by one like so:
```vue
<ContentRenderer :components="{ Carousel, CarouselContent, CarouselItem }" />
```

```ts
import Carousel from "~/components/ui/carousel/Carousel.vue"
import CarouselContent from "~/components/ui/carousel/CarouselContent.vue"
import CarouselItem from "~/components/ui/carousel/CarouselItem.vue"
```

On the other hand marking some components as global via `nuxt.config.ts` still breaks Clouflare build for me at the very last second:

```
17:31:15.413 | ✨ Upload complete!
-- | --
17:31:18.804 | Success: Assets published!
17:31:22.506 | Error: Failed to publish your Function. Got error: Uncaught ReferenceError: require is not defined   at chunks/nitro/nitro.mjs:1:520716
```
