### ISSUE TITLE
No grammar provided for <source.java>

### ISSUE THREAD

**Issue by Mokkapps** [nuxt/content#2351]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.7.4
- CLI Version:      3.9.0
- Nitro Version:    2.6.3
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      modules, content
- Runtime Modules:  @nuxt/content@2.8.4
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-5xzrht?file=content%2Findex.md

## Expected Behavior
Nuxt throws an error if `java` is used as code highlighting language:

[nuxt] [request error] [unhandled] [500] No grammar provided for <source.java>
  at a (./node_modules/shikiji/dist/core.mjs:452:15520)  
  at t.ScopeDependencyProcessor.processQueue (./node_modules/shikiji/dist/core.mjs:452:17212)  
  at Registry._loadGrammar (./node_modules/shikiji/dist/core.mjs:452:30884)  
  at async Registry.loadLanguage (./node_modules/shikiji/dist/core.mjs:567:15)  
  at async Registry.loadLanguages (./node_modules/shikiji/dist/core.mjs:591:7)  
  at async Object.loadLanguage (./node_modules/shikiji/dist/core.mjs:700:5)  
  at async Object.getHighlightedAST (./.nuxt/dev/index.mjs:878:7)  
  at async eval (./.nuxt/dev/index.mjs:939:12)  
  at async Object.eval (./node_modules/h3/dist/index.mjs:1749:19)  

## Expected Behavior
`java` can be used in code blocks to highlight Java code

**Comment by farnabaz** [comment]
Try upgrading to 2.8.5 and adding `java` to `highlight.preload` in `nuxt.config`
```ts
export default defineNuxtConfig({
  content: {
    highlight: {
      preload: ['java'],
    }
  }
}
```

**Comment by wJoenn** [comment]
`v2.8.5` fixed it for me without needing to preload `java`

**Comment by Mokkapps** [comment]
Yes, cannot reproduce it with `2.8.5`: https://stackblitz.com/edit/github-5xzrht-cmab5j?file=content%2Findex.md

**Comment by tcampbPPU** [comment]
had similar issue with `PHP` block, so needed to also upgrade and include that in the preload in the `nuxt.config.ts`
```ts
content: {
  highlight: {
      preload: ['php']
  }
},
```
