### ISSUE TITLE
Build fails on Vercel Edge (`NITRO_PRESET=vercel-edge`)

### ISSUE THREAD

**Issue by arunanshub** [nuxt/content#2408]
### Environment

- Operating System: Linux
- Node Version:     v20.8.0
- Nuxt Version:     3.8.0
- CLI Version:      3.9.1
- Nitro Version:    2.7.2
- Package Manager:  pnpm@8.10.2
- Builder:          -
- User Config:      devtools, srcDir, modules, content, tailwindcss
- Runtime Modules:  @nuxt/content@2.9.0, @nuxtjs/tailwindcss@6.9.3
- Build Modules:    -

### Reproduction

https://github.com/arunanshub/test-nuxt-content

### Describe the bug

The build fails when using `@nuxt/content@>2.8.2` deployed on Vercel Edge Function with error:

```text
The Edge Function "__nitro" is referencing unsupported modules:
 - index.mjs: fs, path
```

### Logs

```shell
[14:18:22.611] Running build in Washington, D.C., USA (East) – iad1 (Hive)
[14:18:22.720] Cloning github.com/arunanshub/test-nuxt-content (Branch: master, Commit: 569462e)
[14:18:23.187] Cloning completed: 467.269ms
[14:18:26.022] Restored build cache
[14:18:26.107] Running "vercel build"
[14:18:26.564] Vercel CLI 32.4.1
[14:18:27.258] Detected `pnpm-lock.yaml` version 6 generated by pnpm 8
[14:18:27.276] Installing dependencies...
[14:18:28.006] Lockfile is up to date, resolution step is skipped
[14:18:28.153] Already up to date
[14:18:28.964] 
[14:18:29.228] 
[14:18:29.228] > nuxt-app@ postinstall /vercel/path0
[14:18:29.228] > nuxt prepare
[14:18:29.228] 
[14:18:31.034] [info] [nuxt:tailwindcss] Using default Tailwind CSS file
[14:18:31.742] [success] Types generated in .nuxt
[14:18:31.758] Done in 4.4s
[14:18:31.795] Running "pnpm run build"
[14:18:32.298] 
[14:18:32.298] > nuxt-app@ build /vercel/path0
[14:18:32.298] > nuxt build
[14:18:32.298] 
[14:18:32.538] [log] Nuxt 3.8.0 with Nitro 2.7.2
[14:18:33.622] [info] [nuxt:tailwindcss] Using default Tailwind CSS file
[14:18:34.974] [info] Building client...
[14:18:35.098] [info]  vite v4.5.0  building for production...  
[14:18:35.132] [info] transforming...
[14:18:38.487] [info]  ✓  267 modules transformed.
[14:18:38.644] [info] rendering chunks...
[14:18:38.756] [info] computing gzip size...
[14:18:38.778] [info]  ../.nuxt/dist/client/  manifest.json                                      27.47 kB     │ gzip:  1.77 kB 
[14:18:38.778] [info]  ../.nuxt/dist/client/  _nuxt/  ProsePre.e63e49c6.css                         0.05 kB     │ gzip:  0.07 kB 
[14:18:38.778] [info]  ../.nuxt/dist/client/  _nuxt/  error-500.20b77af2.css                        2.04 kB     │ gzip:  0.76 kB 
[14:18:38.778] [info]  ../.nuxt/dist/client/  _nuxt/  error-404.6e3501ce.css                        3.72 kB     │ gzip:  1.14 kB 
[14:18:38.778] [info]  ../.nuxt/dist/client/  _nuxt/  ProseCode.91b1d89a.js                         0.10 kB     │ gzip:  0.11 kB 
[14:18:38.778] [info]  ../.nuxt/dist/client/  _nuxt/  ProseHr.459b8362.js                           0.15 kB     │ gzip:  0.14 kB 
[14:18:38.779] [info]  ../.nuxt/dist/client/  _nuxt/  DocumentDrivenNotFound.a8080b78.js            0.16 kB     │ gzip:  0.15 kB 
[14:18:38.780] [info]  ../.nuxt/dist/client/  _nuxt/  ContentRendererMarkdown.db2a15ba.js           0.17 kB     │ gzip:  0.15 kB 
[14:18:38.780] [info]  ../.nuxt/dist/client/  _nuxt/  ProseTr.d9a83beb.js                           0.18 kB     │ gzip:  0.16 kB 
[14:18:38.780] [info]  ../.nuxt/dist/client/  _nuxt/  ProseP.3601d5e4.js                            0.19 kB     │ gzip:  0.16 kB 
[14:18:38.780] [info]  ../.nuxt/dist/client/  _nuxt/  ProseTh.af2e3ef7.js                           0.19 kB     │ gzip:  0.16 kB 
[14:18:38.781] [info]  ../.nuxt/dist/client/  _nuxt/  ProseUl.29d4c966.js                           0.19 kB     │ gzip:  0.16 kB 
[14:18:38.781] [info]  ../.nuxt/dist/client/  _nuxt/  ProseEm.1a65abe5.js                           0.19 kB     │ gzip:  0.16 kB 
[14:18:38.781] [info]  ../.nuxt/dist/client/  _nuxt/  ProseOl.7c9f3008.js                           0.19 kB     │ gzip:  0.16 kB 
[14:18:38.781] [info]  ../.nuxt/dist/client/  _nuxt/  ProseTd.8c6b80a0.js                           0.19 kB     │ gzip:  0.16 kB 
[14:18:38.781] [info]  ../.nuxt/dist/client/  _nuxt/  ProseLi.fa4b6410.js                           0.19 kB     │ gzip:  0.16 kB 
[14:18:38.781] [info]  ../.nuxt/dist/client/  _nuxt/  ProseCodeInline.bd535741.js                   0.19 kB     │ gzip:  0.17 kB 
[14:18:38.781] [info]  ../.nuxt/dist/client/  _nuxt/  ProseThead.4663bc2e.js                        0.19 kB     │ gzip:  0.17 kB 
[14:18:38.781] [info]  ../.nuxt/dist/client/  _nuxt/  ProseTbody.106861da.js                        0.19 kB     │ gzip:  0.17 kB 
[14:18:38.781] [info]  ../.nuxt/dist/client/  _nuxt/  ProseTable.7159d13e.js                        0.19 kB     │ gzip:  0.17 kB 
[14:18:38.782] [info]  ../.nuxt/dist/client/  _nuxt/  ProseBlockquote.a57d56f8.js                   0.19 kB     │ gzip:  0.17 kB 
[14:18:38.782] [info]  ../.nuxt/dist/client/  _nuxt/  ProseStrong.619332e4.js                       0.19 kB     │ gzip:  0.17 kB 
[14:18:38.782] [info]  ../.nuxt/dist/client/  _nuxt/  DocumentDrivenEmpty.fc811314.js               0.29 kB     │ gzip:  0.24 kB 
[14:18:38.782] [info]  ../.nuxt/dist/client/  _nuxt/  ProseCode.vue.f05a315d.js                     0.32 kB     │ gzip:  0.22 kB 
[14:18:38.782] [info]  ../.nuxt/dist/client/  _nuxt/  Markdown.9cb93fba.js                          0.33 kB     │ gzip:  0.26 kB 
[14:18:38.782] [info]  ../.nuxt/dist/client/  _nuxt/  index.3aa9216e.js                             0.36 kB     │ gzip:  0.27 kB 
[14:18:38.782] [info]  ../.nuxt/dist/client/  _nuxt/  vue.f36acd1f.428a00ff.js                      0.39 kB     │ gzip:  0.27 kB 
[14:18:38.782] [info]  ../.nuxt/dist/client/  _nuxt/  ProseA.8716ff74.js                            0.40 kB     │ gzip:  0.28 kB 
[14:18:38.782] [info]  ../.nuxt/dist/client/  _nuxt/  ProseH1.37ab4711.js                           0.44 kB     │ gzip:  0.32 kB 
[14:18:38.782] [info]  ../.nuxt/dist/client/  _nuxt/  ProseH2.067d4186.js                           0.45 kB     │ gzip:  0.32 kB 
[14:18:38.782] [info]  ../.nuxt/dist/client/  _nuxt/  ProseH4.f236179a.js                           0.45 kB     │ gzip:  0.32 kB 
[14:18:38.783] [info]  ../.nuxt/dist/client/  _nuxt/  ProseH3.9386ed44.js                           0.45 kB     │ gzip:  0.32 kB 
[14:18:38.783] [info]  ../.nuxt/dist/client/  _nuxt/  ProseH5.e381d35f.js                           0.45 kB     │ gzip:  0.32 kB 
[14:18:38.783] [info]  ../.nuxt/dist/client/  _nuxt/  ProseH6.ded25422.js                           0.45 kB     │ gzip:  0.32 kB 
[14:18:38.783] [info]  ../.nuxt/dist/client/  _nuxt/  ProseScript.6361e596.js                       0.49 kB     │ gzip:  0.33 kB 
[14:18:38.783] [info]  ../.nuxt/dist/client/  _nuxt/  ProseImg.26aeb371.js                          0.62 kB     │ gzip:  0.37 kB 
[14:18:38.783] [info]  ../.nuxt/dist/client/  _nuxt/  index.288f722b.js                             0.72 kB     │ gzip:  0.40 kB 
[14:18:38.783] [info]  ../.nuxt/dist/client/  _nuxt/  ProsePre.9e3be223.js                          0.74 kB     │ gzip:  0.39 kB 
[14:18:38.783] [info]  ../.nuxt/dist/client/  _nuxt/  ContentList.3a52178d.js                       0.90 kB     │ gzip:  0.49 kB 
[14:18:38.783] [info]  ../.nuxt/dist/client/  _nuxt/  ContentRenderer.6726f8fe.js                   1.27 kB     │ gzip:  0.64 kB 
[14:18:38.784] [info]  ../.nuxt/dist/client/  _nuxt/  _article_.c1ac7163.js                         1.58 kB     │ gzip:  0.91 kB 
[14:18:38.784] [info]  ../.nuxt/dist/client/  _nuxt/  error-500.00cdec19.js                         1.92 kB     │ gzip:  1.01 kB 
[14:18:38.784] [info]  ../.nuxt/dist/client/  _nuxt/  ContentSlot.ff4aa19f.js                       1.95 kB     │ gzip:  0.91 kB 
[14:18:38.784] [info]  ../.nuxt/dist/client/  _nuxt/  ContentDoc.f56b8109.js                        2.10 kB     │ gzip:  0.98 kB 
[14:18:38.784] [info]  ../.nuxt/dist/client/  _nuxt/  ContentNavigation.294196b8.js                 2.19 kB     │ gzip:  1.11 kB 
[14:18:38.784] [info]  ../.nuxt/dist/client/  _nuxt/  error-404.70574ba3.js                         2.30 kB     │ gzip:  1.18 kB 
[14:18:38.784] [info]  ../.nuxt/dist/client/  _nuxt/  ContentQuery.3037fa3a.js                      2.49 kB     │ gzip:  1.03 kB 
[14:18:38.784] [info]  ../.nuxt/dist/client/  _nuxt/  preview.2a429e9a.js                           3.44 kB     │ gzip:  1.45 kB 
[14:18:38.784] [info]  ../.nuxt/dist/client/  _nuxt/  nuxt-link.307827d1.js                         4.05 kB     │ gzip:  1.72 kB 
[14:18:38.784] [info]  ../.nuxt/dist/client/  _nuxt/  query.7c2c82a5.js                            15.30 kB     │ gzip:  6.30 kB 
[14:18:38.786] [info]  ../.nuxt/dist/client/  _nuxt/  client-db.32fcd44d.js                        20.72 kB     │ gzip:  8.57 kB 
[14:18:38.786] [info]  ../.nuxt/dist/client/  _nuxt/  ContentRendererMarkdown.vue.fec2ec04.js      23.54 kB     │ gzip:  8.38 kB 
[14:18:38.786] [info]  ../.nuxt/dist/client/  _nuxt/  entry.c3fff061.js                           151.02 kB     │ gzip: 56.53 kB 
[14:18:38.786] [info]  ✓ built in 3.68s 
[14:18:38.786] [success] Client built in 3807ms
[14:18:38.786] [info] Building server...
[14:18:38.788] [info]  vite v4.5.0  building SSR bundle for production...  
[14:18:38.800] [info] transforming...
[14:18:41.173] [info]  ✓  190 modules transformed.
[14:18:41.250] [info] rendering chunks...
[14:18:41.411] [info]  ../.nuxt/dist/server/  _nuxt/  entry-styles.35674fe0.mjs                0.08 kB   
[14:18:41.411] [info]  ../.nuxt/dist/server/  _nuxt/  ProseCode-styles.93005832.mjs            0.08 kB   
[14:18:41.411] [info]  ../.nuxt/dist/server/  _nuxt/  ProsePre-styles.9d8d359a.mjs             0.15 kB   
[14:18:41.411] [info]  ../.nuxt/dist/server/  _nuxt/  error-404-styles.2ab5d327.mjs            0.15 kB   
[14:18:41.411] [info]  ../.nuxt/dist/server/  _nuxt/  error-500-styles.6b5c9ac9.mjs            0.15 kB   
[14:18:41.412] [info]  ../.nuxt/dist/server/  styles.mjs                                     1.03 kB   
[14:18:41.412] [info]  ../.nuxt/dist/server/  _nuxt/  ProsePre-styles-1.mjs-2476b8a8.js        0.22 kB     │ map:   0.12 kB 
[14:18:41.412] [info]  ../.nuxt/dist/server/  _nuxt/  ProseCode-styles-1.mjs-ef625421.js       0.23 kB     │ map:   0.12 kB 
[14:18:41.412] [info]  ../.nuxt/dist/server/  _nuxt/  DocumentDrivenNotFound-9fc9ac21.js       0.69 kB     │ map:   0.61 kB 
[14:18:41.412] [info]  ../.nuxt/dist/server/  _nuxt/  DocumentDrivenEmpty-1bacd126.js          0.88 kB     │ map:   1.00 kB 
[14:18:41.412] [info]  ../.nuxt/dist/server/  _nuxt/  index-6a088328.js                        0.98 kB     │ map:   6.02 kB 
[14:18:41.413] [info]  ../.nuxt/dist/server/  _nuxt/  ProseHr-f71a9480.js                      1.02 kB     │ map:   0.13 kB 
[14:18:41.413] [info]  ../.nuxt/dist/server/  _nuxt/  Markdown-2366ca77.js                     1.07 kB     │ map:   0.13 kB 
[14:18:41.413] [info]  ../.nuxt/dist/server/  _nuxt/  island-renderer-32021951.js              1.09 kB     │ map:   1.42 kB 
[14:18:41.413] [info]  ../.nuxt/dist/server/  _nuxt/  ProseP-1a33b4f2.js                       1.12 kB     │ map:   0.13 kB 
[14:18:41.413] [info]  ../.nuxt/dist/server/  _nuxt/  ProseLi-a67c2500.js                      1.12 kB     │ map:   0.13 kB 
[14:18:41.413] [info]  ../.nuxt/dist/server/  _nuxt/  ProseOl-481f4dbd.js                      1.12 kB     │ map:   0.13 kB 
[14:18:41.413] [info]  ../.nuxt/dist/server/  _nuxt/  ProseTd-16eb31c5.js                      1.12 kB     │ map:   0.13 kB 
[14:18:41.413] [info]  ../.nuxt/dist/server/  _nuxt/  ProseTh-2b912bbd.js                      1.12 kB     │ map:   0.13 kB 
[14:18:41.414] [info]  ../.nuxt/dist/server/  _nuxt/  ProseEm-c8a26306.js                      1.12 kB     │ map:   0.13 kB 
[14:18:41.414] [info]  ../.nuxt/dist/server/  _nuxt/  ProseTr-e30debc3.js                      1.12 kB     │ map:   0.13 kB 
[14:18:41.414] [info]  ../.nuxt/dist/server/  _nuxt/  ProseUl-0e7aadc3.js                      1.12 kB     │ map:   0.13 kB 
[14:18:41.414] [info]  ../.nuxt/dist/server/  _nuxt/  ProseTable-e1fd3fe7.js                   1.14 kB     │ map:   0.13 kB 
[14:18:41.414] [info]  ../.nuxt/dist/server/  _nuxt/  ProseTbody-353b0586.js                   1.14 kB     │ map:   0.13 kB 
[14:18:41.414] [info]  ../.nuxt/dist/server/  _nuxt/  ProseThead-d6daf55a.js                   1.14 kB     │ map:   0.13 kB 
[14:18:41.414] [info]  ../.nuxt/dist/server/  _nuxt/  ProseStrong-b0d7568e.js                  1.15 kB     │ map:   0.13 kB 
[14:18:41.414] [info]  ../.nuxt/dist/server/  _nuxt/  ProseBlockquote-dc8aa094.js              1.17 kB     │ map:   0.14 kB 
[14:18:41.415] [info]  ../.nuxt/dist/server/  _nuxt/  ProseScript-045839f4.js                  1.18 kB     │ map:   0.75 kB 
[14:18:41.415] [info]  ../.nuxt/dist/server/  _nuxt/  ProseCodeInline-9375eaab.js              1.18 kB     │ map:   0.14 kB 
[14:18:41.415] [info]  ../.nuxt/dist/server/  _nuxt/  ProseCode-11e696ba.js                    1.21 kB     │ map:   0.14 kB 
[14:18:41.415] [info]  ../.nuxt/dist/server/  _nuxt/  index-7798e948.js                        1.42 kB     │ map:   0.36 kB 
[14:18:41.415] [info]  ../.nuxt/dist/server/  _nuxt/  ProseH1-04a62571.js                      1.73 kB     │ map:   0.85 kB 
[14:18:41.415] [info]  ../.nuxt/dist/server/  _nuxt/  ProseH2-845705cb.js                      1.74 kB     │ map:   0.85 kB 
[14:18:41.415] [info]  ../.nuxt/dist/server/  _nuxt/  ProseH3-c1766bdd.js                      1.74 kB     │ map:   0.85 kB 
[14:18:41.415] [info]  ../.nuxt/dist/server/  _nuxt/  ProseH4-523d57ac.js                      1.74 kB     │ map:   0.85 kB 
[14:18:41.416] [info]  ../.nuxt/dist/server/  _nuxt/  ProseH6-3df28ef0.js                      1.74 kB     │ map:   0.85 kB 
[14:18:41.416] [info]  ../.nuxt/dist/server/  _nuxt/  ProseH5-504aaf6c.js                      1.74 kB     │ map:   0.85 kB 
[14:18:41.416] [info]  ../.nuxt/dist/server/  _nuxt/  ProseA-bf3c3c08.js                       1.79 kB     │ map:   0.16 kB 
[14:18:41.416] [info]  ../.nuxt/dist/server/  _nuxt/  ProseImg-b95e433d.js                     1.99 kB     │ map:   1.50 kB 
[14:18:41.416] [info]  ../.nuxt/dist/server/  _nuxt/  error-500-styles-1.mjs-9d7f5c1d.js       2.26 kB     │ map:   0.12 kB 
[14:18:41.416] [info]  ../.nuxt/dist/server/  _nuxt/  ProsePre-7cf7b061.js                     2.36 kB     │ map:   0.18 kB 
[14:18:41.416] [info]  ../.nuxt/dist/server/  _nuxt/  preview-7814b866.js                      2.46 kB     │ map:   7.77 kB 
[14:18:41.416] [info]  ../.nuxt/dist/server/  _nuxt/  ContentList-8ba2b688.js                  2.79 kB     │ map:   2.99 kB 
[14:18:41.417] [info]  ../.nuxt/dist/server/  _nuxt/  error-500-9c62ce92.js                    3.15 kB     │ map:   3.83 kB 
[14:18:41.417] [info]  ../.nuxt/dist/server/  _nuxt/  ContentRenderer-848ab640.js              3.23 kB     │ map:   3.55 kB 
[14:18:41.417] [info]  ../.nuxt/dist/server/  _nuxt/  _article_-921cd433.js                    3.76 kB     │ map:   7.62 kB 
[14:18:41.417] [info]  ../.nuxt/dist/server/  _nuxt/  error-404-styles-1.mjs-f693ae56.js       3.96 kB     │ map:   0.12 kB 
[14:18:41.417] [info]  ../.nuxt/dist/server/  _nuxt/  error-404-82e2c0c0.js                    4.05 kB     │ map:   5.87 kB 
[14:18:41.417] [info]  ../.nuxt/dist/server/  _nuxt/  ContentSlot-1917bffe.js                  4.98 kB     │ map:   8.22 kB 
[14:18:41.418] [info]  ../.nuxt/dist/server/  _nuxt/  ContentNavigation-2c6ac007.js            5.01 kB     │ map:   8.19 kB 
[14:18:41.418] [info]  ../.nuxt/dist/server/  _nuxt/  nuxt-link-e8ce45ca.js                    6.03 kB     │ map:  13.90 kB 
[14:18:41.418] [info]  ../.nuxt/dist/server/  _nuxt/  ContentQuery-1d852bb5.js                 6.32 kB     │ map:   9.09 kB 
[14:18:41.418] [info]  ../.nuxt/dist/server/  _nuxt/  ContentDoc-5797b0b5.js                   7.66 kB     │ map:  11.05 kB 
[14:18:41.418] [info]  ../.nuxt/dist/server/  _nuxt/  query-36b7fb70.js                       12.81 kB     │ map:  30.11 kB 
[14:18:41.418] [info]  ../.nuxt/dist/server/  _nuxt/  ContentRendererMarkdown-761d19bd.js     13.68 kB     │ map:  21.58 kB 
[14:18:41.418] [info]  ../.nuxt/dist/server/  _nuxt/  client-db-7393ee20.js                   15.77 kB     │ map:  29.33 kB 
[14:18:41.418] [info]  ../.nuxt/dist/server/  _nuxt/  entry-styles-1.mjs-32ea175f.js          16.87 kB     │ map:   0.11 kB 
[14:18:41.418] [info]  ../.nuxt/dist/server/  server.mjs                                    43.67 kB     │ map: 106.51 kB 
[14:18:41.419] [info]  ✓ built in 2.62s 
[14:18:41.424] [success] Server built in 2640ms
[14:18:41.466] [success] [nitro] Generated public .vercel/output/static
[14:18:41.467] [info] [nitro] Initializing prerenderer
[14:18:44.898] [info] [nitro] Prerendering 1 routes
[14:18:45.363] [log] [nitro]   ├─ /api/_content/cache.1699001313471.json (442ms)
[14:18:45.484] [info] [nitro] Building Nitro Server (preset: `vercel-edge`)
[14:19:33.724] [success] [nitro] Nitro server built
[14:19:34.149]   ├─ .vercel/output/functions/__nitro.func/b1644a9e745f1309.wasm (467 kB) (148 kB gzip)
[14:19:34.149]   └─ .vercel/output/functions/__nitro.func/index.mjs (7.86 MB) (1.65 MB gzip)
[14:19:34.149] Σ Total size: 8.33 MB (1.8 MB gzip)
[14:19:34.402] Build Completed in /vercel/output [1m]
[14:19:34.512] Deploying outputs...
[14:19:36.778] Error: The Edge Function "__nitro" is referencing unsupported modules:
[14:19:36.779] 	- index.mjs: fs, path
```

**Comment by Neo-Zhixing** [comment]
Was able to replicate.

**Comment by arunanshub** [comment]
@Neo-Zhixing This appears to be the case with platforms that use Cloudflare. Also, Cloudflare is used by Vercel.

**Comment by alexgrozav** [comment]
I'm encountering this as well. 

Related issue (linking here to point people to this one): https://github.com/nuxt/nuxt/issues/23418

**Comment by yyyanghj** [comment]
Same here.

**Comment by Lexpeartha** [comment]
Can confirm this on my end as well 👍🏽 
![image](https://github.com/nuxt/content/assets/43365376/b8f39132-26f1-4a2a-844e-d41ba1f19f16)

All of the edge presets behave like this from my testing

**Comment by yyyanghj** [comment]
I got some discovery maybe helpful.


I diged the build output of [this reproduction](https://github.com/silvio-e/nuxt-3-7-4), the problem seems to be here.

<img width="1013" alt="SCR-20231119-dwhu" src="https://github.com/nuxt/content/assets/34713301/0fdadd4f-4623-42fc-b7a1-5efb622cf6ec">

<br/>
<br/>

This looks like @rollup/plugin-wasm [code](https://github.com/rollup/plugins/blob/2c58b01a45d31e0abd72c9c83a86c826c898cd24/packages/wasm/src/helper.ts#L5), and this plugin is used by nitropack.
```sh
pnpm why @rollup/plugin-wasm 

devDependencies:
@nuxt/devtools 0.8.5
├─┬ @nuxt/devtools-kit 0.8.5
│ └─┬ nuxt 3.7.4 peer
│   └─┬ nitropack 2.6.3
│     └── @rollup/plugin-wasm 6.2.1
└─┬ nuxt 3.7.4 peer
  └─┬ nitropack 2.6.3
    └── @rollup/plugin-wasm 6.2.1
nuxt 3.7.4
└─┬ nitropack 2.6.3
  └── @rollup/plugin-wasm 6.2.1
```

FYI.

**Comment by yyyanghj** [comment]
> code

Hey guys, a workaround for this issue.

```ts
// nuxt.config.ts

export default defineNuxtConfig({
  nitro: {
    preset: 'vercel-edge',
    wasm: {
      rollup: {
        targetEnv: 'browser'
      }
    }
  }
})
```

**Comment by yyyanghj** [comment]
> While this does work, it increases build size **drastically** so be aware of this

https://github.com/nuxt/content/issues/2439

**Comment by pontsci** [comment]
Similar issue here with rollup, different error but same result, build fails.
```
 ERROR  Cannot read properties of undefined (reading 'split')  6:45:01 PM  

  at /node_modules/@rollup/plugin-inject/dist/es/index.js:74:74
  at Map.forEach (<anonymous>)
  at inject (/node_modules/@rollup/plugin-inject/dist/es/index.js:71:16)
  at getRollupConfig (/node_modules/nitropack/dist/shared/nitro.4ea992bc.mjs:2037:29)
  at build (//node_modules/nitropack/dist/shared/nitro.4ea992bc.mjs:2333:24)
  at /node_modules/nuxt/dist/index.mjs:2994:13
  at async build (/node_modules/nuxt/dist/index.mjs:4389:5)
  at async Object.run (/node_modules/nuxi/dist/chunks/build.mjs:98:5)
  at async runCommand$1 (/node_modules/nuxi/dist/shared/nuxi.4fde776c.mjs:1648:16)
  at async runCommand$1 (/node_modules/nuxi/dist/shared/nuxi.4fde776c.mjs:1639:11)
```

Points to this section of code where split is called in the rollup module:
```
  // Fix paths on Windows
  if (sep !== '/') {
    modulesMap.forEach(function (mod, key) {
      modulesMap.set(
        key,
        Array.isArray(mod) ? [mod[0].split(sep).join('/'), mod[1]] : mod.split(sep).join('/')
      );
    });
  }
```

**Comment by medaminefh** [comment]
Is anyone has a solution for this yet ?
![Screenshot from 2024-02-29 12-33-03](https://github.com/nuxt/content/assets/37845480/f69e7575-13bf-44b5-ba01-353c989c4860)

**Comment by arunanshub** [comment]
@medaminefh upgrade to latest nuxt/content. It seems to work fine with vercel edge.

**Comment by medaminefh** [comment]
@arunanshub I'm not using Nuxt/content in my project
