### ISSUE TITLE
nuxt storybook and nuxt content dont play nice

### ISSUE THREAD

**Issue by jpengelbrecht** [nuxt/content#2504]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v18.10.0
- Nuxt Version:     3.9.1
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  pnpm@8.11.0
- Builder:          -
- User Config:      modules, sourcemap, devServer, devtools
- Runtime Modules:  @nuxt/content@2.10.0, @nuxtjs/storybook@7.0.0
- Build Modules:    -
------------------------------

### Reproduction

https://github.com/jpengelbrecht/nuxt-seo-route-rules-issue/tree/nuxt-content-and-story-book-cant-play-nice

### Describe the bug

<img width="994" alt="image" src="https://github.com/nuxt-modules/storybook/assets/93583336/b7f0a257-bec3-4037-b766-330659d929e7">

installing both   modules: [
    "@nuxt/content",
    "@nuxtjs/storybook",
  ],

will break `npm run dev` and result in the above error.  it also breaks` npm run storybook` find reprodction here. https://github.com/jpengelbrecht/nuxt-seo-route-rules-issue/tree/nuxt-content-and-story-book-cant-play-nice

[nitro] ✔ Generated public .output/public
[nitro] ℹ Building Nitro Server (preset: node-server)
(alias plugin) rewrote #mdc-imports to file:///Users/jean-pierre/Projects/site-main/.nuxt/mdc-imports.mjs but was not an abolute path and was not handled by other plugins. This will lead to duplicated modules for the same path. To avoid duplicating modules, you should resolve to an absolute path.
(alias plugin) rewrote #mdc-imports to file:///Users/jean-pierre/Projects/site-main/.nuxt/mdc-imports.mjs but was not an abolute path and was not handled by other plugins. This will lead to duplicated modules for the same path. To avoid duplicating modules, you should resolve to an absolute path.

[nitro]  ERROR  Error: Could not load file:///Users/jean-pierre/Projects/site-main/.nuxt/mdc-imports.mjs (imported by node_modules/@nuxtjs/mdc/dist/runtime/parser/index.mjs): ENOENT: no such file or directory, open 'file:///Users/jean-pierre/Projects/site-main/.nuxt/mdc-imports.mjs'

undefined

=> Failed to build the preview
Error: Error: Could not load file://./.nuxt/mdc-imports.mjs (imported by node_modules/@nuxtjs/mdc/dist/runtime/parser/index.mjs): ENOENT: no such file or directory, open 'file://./.nuxt/mdc-imports.mjs'
    at defineNuxtConfig (./node_modules/.pnpm/@storybook-vue+nuxt@0.2.0_@types+node@20.11.3_@vue+compiler-core@3.4.14_eslint@8.56.0_nuxt@3._ozvbtwmhvmux5ilcf4zf4co6ja/node_modules/@storybook-vue/nuxt/dist/preset.cjs:6594:11)
    at async Object.viteFinal (./node_modules/.pnpm/@storybook-vue+nuxt@0.2.0_@types+node@20.11.3_@vue+compiler-core@3.4.14_eslint@8.56.0_nuxt@3._ozvbtwmhvmux5ilcf4zf4co6ja/node_modules/@storybook-vue/nuxt/dist/preset.cjs:6615:22)
    at async createViteServer (./node_modules/.pnpm/@storybook+builder-vite@7.5.3_typescript@5.3.3_vite@5.0.11/node_modules/@storybook/builder-vite/dist/index.js:159:10518)
    at async Module.start (./node_modules/.pnpm/@storybook+builder-vite@7.5.3_typescript@5.3.3_vite@5.0.11/node_modules/@storybook/builder-vite/dist/index.js:159:12520)
    at async storybookDevServer (./node_modules/.pnpm/@storybook+core-server@7.5.3/node_modules/@storybook/core-server/dist/index.js:104:2460)
    at async buildDevStandalone (./node_modules/.pnpm/@storybook+core-server@7.5.3/node_modules/@storybook/core-server/dist/index.js:119:3007)
    at async withTelemetry (./node_modules/.pnpm/@storybook+core-server@7.5.3/node_modules/@storybook/core-server/dist/index.js:103:3903)
    at async dev (./node_modules/.pnpm/@storybook+cli@7.5.3/node_modules/@storybook/cli/dist/generate.js:473:401)
    at async Command.<anonymous> (./node_modules/.pnpm/@storybook+cli@7.5.3/node_modules/@storybook/cli/dist/generate.js:475:225)

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.

_No response_

**Comment by bahulneel** [comment]
I solved this by installing `@nuxt/mdc@latest`.
