### ISSUE TITLE
Unable to install nuxt with @nuxt/content with pnpm

### ISSUE THREAD

**Issue by scottcarlton** [nuxt/content#2733]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.20.2`
- Nuxt Version:     `3.12.3`
- CLI Version:      `3.12.0`
- Nitro Version:    `2.9.7`
- Package Manager:  `pnpm@9.5.0`
- Builder:          `-`
- User Config:      `compatibilityDate`, `devtools`, `modules`
- Runtime Modules:  `@nuxt/content@2.13.2`, `@nuxt/image@1.7.0`
- Build Modules:    `-`

### Reproduction

`pnpm dlx nuxi@latest init <project-name>`
`cd <project-name>`
`pnpm add @nuxt/content`

```
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  compatibilityDate: '2024-04-03',
  devtools: { enabled: true },
  modules: ['@nuxt/content', "@nuxt/image"],
  content: {}
})
```

### Describe the bug

`(index):88  GET http://localhost:3000/ 503 (Service Unavailable)`

```
ERROR  [worker reload] [worker init] Cannot find package 'unified' imported from /Users/username/Sites/<project-name>/.nuxt/dev/index.mjs
Did you mean to import unified@11.0.5/node_modules/unified/index.js?

  Did you mean to import unified@11.0.5/node_modules/unified/index.js?
  at __node_internal_captureLargerStackTrace (node:internal/errors:496:5)
  at new NodeError (node:internal/errors:405:5)
  at packageResolve (node:internal/modules/esm/resolve:916:9)
  at moduleResolve (node:internal/modules/esm/resolve:973:20)
  at defaultResolve (node:internal/modules/esm/resolve:1193:11)
  at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:404:12)
  at ModuleLoader.resolve (node:internal/modules/esm/loader:373:25)
  at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:250:38)
  at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:39)
  at link (node:internal/modules/esm/module_job:75:36)
```

### Additional context

Not sure what else I can add here since this is just basic setup stuff.

**Comment by gustawdaniel** [comment]
Closing issues as not planned is not a solution.

https://github.com/nuxt/content/issues/3329

I hae problem with nuxt content and pnpm 10

```
 ERROR  Could not load @nuxt/content. Is it installed?                                                                        11:25:08 AM

    at loadNuxtModuleInstance (/home/daniel/pro/open_cash_manager/node_modules/@nuxt/kit/dist/index.mjs:665:118)
    at async installModules (/home/daniel/pro/open_cash_manager/node_modules/@nuxt/kit/dist/index.mjs:482:15)
    at async initNuxt (/home/daniel/pro/open_cash_manager/node_modules/nuxt/dist/index.mjs:6033:3)
    at async #initializeNuxt (/home/daniel/pro/open_cash_manager/node_modules/@nuxt/cli/dist/dev-ChFC_-E8.mjs:493:3)
    at async NuxtDevServer.init (/home/daniel/pro/open_cash_manager/node_modules/@nuxt/cli/dist/dev-ChFC_-E8.mjs:385:3)
    at async initialize (/home/daniel/pro/open_cash_manager/node_modules/@nuxt/cli/dist/dev-ChFC_-E8.mjs:687:2)
    at async Object.run (/home/daniel/pro/open_cash_manager/node_modules/@nuxt/cli/dist/dev-bt4if7SS.mjs:205:51)
    at async runCommand (/home/daniel/pro/open_cash_manager/node_modules/@nuxt/cli/node_modules/citty/dist/index.mjs:188:47)
    at async runCommand (/home/daniel/pro/open_cash_manager/node_modules/@nuxt/cli/node_modules/citty/dist/index.mjs:185:21)
    at async runMain (/home/daniel/pro/open_cash_manager/node_modules/@nuxt/cli/node_modules/citty/dist/index.mjs:285:10) 
```
