### ISSUE TITLE
Latest update (v2.13.3) causes build error in production

### ISSUE THREAD

**Issue by ptdev** [nuxt/content#2811]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v20.18.0
- Nuxt Version:     3.13.2
- CLI Version:      3.14.0
- Nitro Version:    2.9.7
- Package Manager:  yarn@4.5.0
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

1. Update to latest version
2. Run production build

### Describe the bug

After updating to the latest version (v2.13.3), running yarn build in production causes the following error:

```js
ERROR  x Build failed in 4.88s                                                                     1:48:21 PM


[1:48:21 PM]  ERROR  Nuxt Build Error: [vite]: Rollup failed to resolve import "#components" from "virtual:nuxt:/***********/node_modules/.cache/nuxt/.nuxt/mdc-image-component.mjs".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
build.rollupOptions.external

  This is most likely unintended because it can break your application at runtime.
  If you do want to externalize this module explicitly add it to
  build.rollupOptions.external
  at viteWarn (node_modules/vite/dist/node/chunks/dep-Cyk9bIUq.js:65578:17)
  at onRollupWarning (node_modules/vite/dist/node/chunks/dep-Cyk9bIUq.js:65610:5)
  at onwarn (node_modules/vite/dist/node/chunks/dep-Cyk9bIUq.js:65273:7)
  at node_modules/rollup/dist/es/shared/node-entry.js:19393:13
  at Object.logger [as onLog] (node_modules/rollup/dist/es/shared/node-entry.js:21119:9)
  at ModuleLoader.handleInvalidResolvedId (node_modules/rollup/dist/es/shared/node-entry.js:20008:26)
  at node_modules/rollup/dist/es/shared/node-entry.js:19966:26
```

Reverting to the previous version (v2.13.2) fixes the issue.

If we go looking for the file it complains about (project/node_modules/.cache/nuxt/.nuxt/mdc-image-component.mjs) it does not exist in that folder.

### Additional context

Probably related to the upgrading of @nuxtjs/mdc

**Comment by farnabaz** [comment]
Thanks for the report, Indeed it is related to MDC module. It should fix in the `@nuxtjs/mdc-edge@latest`.
Could you confirm the fix by adding `"@nuxtjs/mdc": "npm:@nuxtjs/mdc-edge@latest"` resolution to your `package.json`?

**Comment by ptdev** [comment]
Hi,

Thanks for the quick reply.

I've added what you've requested on our package.json yarn resolutions section but now we get another error:

```js
ERROR  x Build failed in 6.96s                                                                                                   2:35:27 PM


[2:35:27 PM]  ERROR  Nuxt Build Error: node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseImg.vue?vue&type=script&setup=true&lang.ts (5:9): "default" is not exported by "node_modules/.cache/nuxt/.nuxt/mdc-image-component.mjs", imported by "node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseImg.vue?vue&type=script&setup=true&lang.ts".
file: /*****/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseImg.vue?vue&type=script&setup=true&lang.ts:5:9

3: 
4: import { withTrailingSlash, withLeadingSlash, joinURL } from 'ufo'
5: import { useRuntimeConfig, computed } from '#imports'
            ^
6: 
7: import ImageComponent from '#build/mdc-image-component.mjs'


  file: node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseImg.vue?vue&type=script&setup=true&lang.ts:5:9
  
  3:
  4: import { withTrailingSlash, withLeadingSlash, joinURL } from 'ufo'
  5: import { useRuntimeConfig, computed } from '#imports'
  ^
  6:
  7: import ImageComponent from '#build/mdc-image-component.mjs'
  
  at getRollupError (node_modules/rollup/dist/es/shared/parseAst.js:395:41)
  at error (node_modules/rollup/dist/es/shared/parseAst.js:391:42)
  at Module.error (node_modules/rollup/dist/es/shared/node-entry.js:15535:16)
  at Module.traceVariable (node_modules/rollup/dist/es/shared/node-entry.js:15984:29)
  at ModuleScope.findVariable (node_modules/rollup/dist/es/shared/node-entry.js:13770:39)
  at ChildScope.findVariable (node_modules/rollup/dist/es/shared/node-entry.js:5252:38)
  at FunctionScope.findVariable (node_modules/rollup/dist/es/shared/node-entry.js:5252:38)
  at FunctionBodyScope.findVariable (node_modules/rollup/dist/es/shared/node-entry.js:5252:38)
  at ReturnValueScope.findVariable (node_modules/rollup/dist/es/shared/node-entry.js:5252:38)
  at FunctionBodyScope.findVariable (node_modules/rollup/dist/es/shared/node-entry.js:5252:38)
```

Cheers

**Comment by farnabaz** [comment]
Thank you for the check, should fix in the new patch `@nuxtjs/mdc-edge@0.9.2-28816666.d3ddc9c`

**Comment by ptdev** [comment]
Hey, 

Confirming that if we place that specific commit on our resolutions, the error is fixed.

Thanks for the quick fix 👍

**Comment by farnabaz** [comment]
Thanks for the confirmation, I'll release a hotfix
