### ISSUE TITLE
Rss rendering ?

### ISSUE THREAD

**Issue by Mikaleb** [nuxt/content#2912]
### Describe the solution you'd like
A simple option to activate rss in nuxt/content

### Describe alternatives you've considered
for now nothing works when doing `import { serverQueryContent } from "#content/server";`

### Additional context

Tried 

```ts
// server/routes/rss.xml.ts
import { serverQueryContent } from "#content/server";
import rss from "rss";

export default defineEventHandler(async (event) => {
  const articles = await serverQueryContent(event, "posts")
    .sort({ date: -1 })
    .find();

  const feed = new rss({
    title: "Your Site Title",
    site_url: "https://your-site.tld",
    feed_url: "https://your-site.tld/rss.xml", // this should match your route path
  });

  for (const article of articles) {
    feed.item({
      title: article.title || "",
      description: article.description,
      date: article.date,
      url: `https://your-site.tld${article._path}`,
    });
  }

  setHeaders(event, { "Content-Type": "application/rss+xml" });
  return feed.xml();
});

```

doing

```
Errors prerendering:
  ├─ /rss.xml (492ms)                                                                                                      nitro 2:49:03 PM
  │ └── [404] 
  ├─ /api/_content/query/0CgxMh2nDn.1734097728668.json (4ms)                                                               nitro 2:49:03 PM
  │ ├── [404] Document not found!
  │ └── Linked from /
  ├─ /api/_content/query/ziwUULXgeJ.1734097728668.json (26ms)                                                              nitro 2:49:03 PM
  │ ├── [404] Document not found!
  │ └── Linked from /posts
  ├─ /rss (132ms)                                                                                                          nitro 2:49:03 PM
  │ ├── [404] 
  │ └── Linked from /posts
                                                                                                                           nitro 2:49:03 PM

 ERROR  Exiting due to prerender errors.                                                                                         2:49:03 PM

  at prerender (node_modules/.pnpm/nitropack@2.10.4_typescript@5.7.2/node_modules/nitropack/dist/core/index.mjs:2054:11)
  at async node_modules/.pnpm/nuxt@3.14.1592_@parcel+watcher@2.5.0_@types+node@22.10.2_eslint@9.16.0_jiti@2.4.1__ioredis@5._7b7qu52zhxgubqappq6372l3zm/node_modules/nuxt/dist/index.mjs:3737:5
  at async build (node_modules/.pnpm/nuxt@3.14.1592_@parcel+watcher@2.5.0_@types+node@22.10.2_eslint@9.16.0_jiti@2.4.1__ioredis@5._7b7qu52zhxgubqappq6372l3zm/node_modules/nuxt/dist/index.mjs:5967:3)
  at async Object.run (node_modules/.pnpm/nuxi@3.16.0/node_modules/nuxi/dist/chunks/build.mjs:104:5)
  at async Object.run (node_modules/.pnpm/nuxi@3.16.0/node_modules/nuxi/dist/chunks/generate.mjs:60:5)
  at async runCommand$1 (node_modules/.pnpm/nuxi@3.16.0/node_modules/nuxi/dist/shared/nuxi.f8a4d1b7.mjs:1648:16)
  at async runCommand$1 (node_modules/.pnpm/nuxi@3.16.0/node_modules/nuxi/dist/shared/nuxi.f8a4d1b7.mjs:1639:11)
  at async runMain$1 (node_modules/.pnpm/nuxi@3.16.0/node_modules/nuxi/dist/shared/nuxi.f8a4d1b7.mjs:1777:7) 
```

**Comment by farnabaz** [comment]
Do you mind providing a reproduction sample? It works fine in my test https://stackblitz.com/edit/github-gmkfzcrc?file=server%2Froutes%2Frss.xml.ts

**Comment by Mikaleb** [comment]
Made it working, fyi if you don't set your settings in nuxt to both be in src : 

```
serverDir: "src/server",
  srcDir: "src/",
```

it won't work (sorry about that)
