### ISSUE TITLE
can't build nuxt-content-3 with nuxthq/studio module configured

### ISSUE THREAD

**Issue by endquote** [nuxt/content#2915]
### Environment

```
------------------------------
- Operating System: Linux
- Node Version:     v22.11.0
- Nuxt Version:     3.14.1592
- CLI Version:      3.16.0
- Nitro Version:    2.10.4
- Package Manager:  pnpm@9.15.0
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------
```

### Reproduction

https://github.com/endquote/vue-content-reload/tree/studio

`package.json`
```
"@nuxt/content": "3.0.0-alpha.8",
"@nuxt/eslint": "0.7.2",
"@nuxthq/studio": "2.2.1",
```

`nuxt.config.ts`
`  modules: ["@nuxt/content", "@nuxt/eslint", "@nuxthq/studio"],`

```
Nuxt Build Error: [commonjs--resolver] [unimport] failed to find "useContentState" imported from "#imports"
file: /workspaces/endquote-nuxt/node_modules/.pnpm/@nuxthq+studio@2.2.1_magicast@0.3.5_rollup@4.27.4/node_modules/@nuxthq/studio/dist/runtime/composables/useStudio.js

  file: node_modules/.pnpm/@nuxthq+studio@2.2.1_magicast@0.3.5_rollup@4.27.4/node_modules/@nuxthq/studio/dist/runtime/composables/useStudio.js
  at node_modules/.pnpm/unimport@3.13.3_rollup@4.27.4/node_modules/unimport/dist/shared/unimport.54fdbc5b.mjs:120:17
  at Array.forEach (<anonymous>)
  at node_modules/.pnpm/unimport@3.13.3_rollup@4.27.4/node_modules/unimport/dist/shared/unimport.54fdbc5b.mjs:117:44
  at Array.forEach (<anonymous>)
  at parseVirtualImportsRegex (node_modules/.pnpm/unimport@3.13.3_rollup@4.27.4/node_modules/unimport/dist/shared/unimport.54fdbc5b.mjs:115:122)
  at detectImportsRegex (node_modules/.pnpm/unimport@3.13.3_rollup@4.27.4/node_modules/unimport/dist/shared/unimport.54fdbc5b.mjs:96:28)
  at async injectImports (node_modules/.pnpm/unimport@3.13.3_rollup@4.27.4/node_modules/unimport/dist/shared/unimport.54fdbc5b.mjs:1387:61)
  at async Object.injectImportsWithContext [as injectImports] (node_modules/.pnpm/unimport@3.13.3_rollup@4.27.4/node_modules/unimport/dist/shared/unimport.54fdbc5b.mjs:1259:20)
  at async Object.transform (node_modules/.pnpm/nuxt@3.14.1592_@libsql+client@0.14.0_@parcel+watcher@2.5.0_@types+node@22.10.0_better-sqlite3_sefqyb3ectblwmt2b3eoe2hb7i/node_modules/nuxt/dist/index.mjs:2633:30)
  at async transform (node_modules/.pnpm/rollup@4.27.4/node_modules/rollup/dist/es/shared/node-entry.js:19663:16)
  at async ModuleLoader.addModuleSource (node_modules/.pnpm/rollup@4.27.4/node_modules/rollup/dist/es/shared/node-entry.js:19879:36)
```

This import seems to be [here](https://github.com/nuxtlabs/studio-module/blob/094651eeea8170217945c4c0655e861597547e8f/src/runtime/composables/useStudio.ts#L10) but I can't find a `useContentState` method anywhere.

### Describe the bug

After configuring Nuxt Studio in a Nuxt Content 3-alpha-8 project, the project no longer builds. The [release notes](https://github.com/nuxt/content/releases/tag/v3.0.0-alpha.8) for alpha 8 note that Nuxt Studio is supported.

### Additional context

Other reports on discord:
https://discord.com/channels/473401852243869706/473406506579263488/1314775372285349919
https://discord.com/channels/473401852243869706/1316057973071548496/1316057973071548496
https://discord.com/channels/473401852243869706/1311713467455115324/1311713467455115324

### Logs

```Shell

```

**Comment by larbish** [comment]
Hey @endquote, `studio` is now an opt-in feature of Nuxt Content v3. You don't need an extra module and `@nuxthq/studio` will be deprecated. Just follow the doc to enable the studio: https://content3.nuxt.dev/docs/studio/setup

**Comment by endquote** [comment]
I see. I was following the documentation on the studio site:
https://nuxt.studio/docs/get-started/setup

It's working for me now.

**Comment by cp-bwg** [comment]
This documentation is still outdated, and led me to a couple of hours of frustration. @larbish mind updating it to save the rest the frustration?

**Comment by avxkim** [comment]
spent a hour to figure out that we don't need @nuxthq/studio module, https://nuxt.com/modules/studio can you update this module description, that it works only with nuxt-content v2?
