### ISSUE TITLE
[V3]When configured with the repository and authToken, content3 can't get the content from the remote repository.

### ISSUE THREAD

**Issue by aatrooox** [nuxt/content#2926]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v18.20.5
- Nuxt Version:     3.14.1592
- CLI Version:      3.16.0
- Nitro Version:    2.10.4
- Package Manager:  npm@10.8.2
- Builder:          -
- User Config:      default
- Runtime Modules:  @nuxt/content@3.0.0-alpha.8, @nuxtjs/tailwindcss@6.12.2, @primevue/nuxt-module@4.2.4, @nuxt/image@1.8.1, @nuxt/icon@1.9.1, @nuxtjs/mdc@0.9.5, @nuxtjs/color-mode@3.5.2
- Build Modules:    -
------------------------------

### Reproduction

Reproducing the problem will expose my accessToken, so please refer to the error description below.

### Describe the bug

At first, I used "cwd" to read the local file directory and everything was just fine. 

But as soon as I set the "repository" and "authToken", there would be error messages popping up. （The GitHub repository is a private repository.
）

And I couldn't find any more tips in the official documentation or on YouTube! 

Please give me a hand!

```ts
export const collections = {
  content: defineCollection({
    type: 'page',
    source: {
      include: '**/*.md',
      exclude: ['**/-*.md'],
      // cwd: process.env.CONTENT_FS_PATH,
      repository: 'https://github.com/aatrooox/xxxxxx',
      authToken: 'xxxxxxxx'
    },
    schema: z.object({
      date: z.date(),
      lastmod: z.date(),
      tags: z.array(z.string()),
      versions: z.array(z.string()),
    })
  })
}
```

error: 

```
 ERROR  [unhandledRejection] TAR_BAD_ARCHIVE: Unrecognized archive format                                                                                                    10:41:48

  at warnMethod (node_modules/tar/dist/esm/warn-method.js:24:42)
  at Unpack.warn (node_modules/tar/dist/esm/parse.js:131:9)
  at Unpack.warn (node_modules/tar/dist/esm/unpack.js:234:22)
  at Unpack.<anonymous> (node_modules/tar/dist/esm/parse.js:94:22)
  at Unpack.emit (node:events:529:35)
  at [emit] (node_modules/tar/dist/esm/parse.js:318:18)
  at [maybeEnd] (node_modules/tar/dist/esm/parse.js:486:23)
  at Unpack.end (node_modules/tar/dist/esm/parse.js:589:31)
  at Pipe.end (node_modules/minipass/dist/esm/index.js:107:23)
  at [emitEnd2] (node_modules/minipass/dist/esm/index.js:818:15)
  at [emitEnd] (node_modules/minipass/dist/esm/index.js:804:29)
  at ReadStream.emit (node_modules/minipass/dist/esm/index.js:753:33)
  at ReadStream.emit (node_modules/@isaacs/fs-minipass/dist/esm/index.js:160:30)
  at [maybeEmitEnd] (node_modules/minipass/dist/esm/index.js:704:18)
  at ReadStream.end (node_modules/minipass/dist/esm/index.js:457:33)
  at [_handleChunk] (node_modules/@isaacs/fs-minipass/dist/esm/index.js:139:19)
  at [_onread] (node_modules/@isaacs/fs-minipass/dist/esm/index.js:113:36)
  at node_modules/@isaacs/fs-minipass/dist/esm/index.js:105:86
  at FSReqCallback.wrapper [as oncomplete] (node:fs:677:5)
```
 I thought it was a problem with Node, so I switched the Node version and reinstalled the node_modules. However, a new error occurred at this time.

```ts
Caused by: SyntaxError: The requested module '/_nuxt/node_modules/debug/src/browser.js?v=ea666774' does not provide an export named 'default' (at create-tokenizer.js?v=ea666774:40:8)

overrideMethod @ hook.js:608
```

So, could you give me some hints? I can't figure out what the cause is. After all, I just changed the configuration.

🙏🙏🙏

### Logs

```Shell

```

**Comment by HugoRCD** [comment]
@aatrooox Can you tell me if you managed to fix the error or not?

**Comment by aatrooox** [comment]
@HugoRCD Yes, I resolved the issue.

 It was my own mistake—I didn't set readable permissions for my repository. 

This kind of error isn't easy to troubleshoot just by looking at the error logs.

When I decided to create a new repository and provide a minimal reproducible example, I realized that I hadn't set the permissions correctly in the GitHub settings.

![](https://img.zzao.club/article/202412231658531.png)

**Comment by HugoRCD** [comment]
@aatrooox Ok thanks, but now I have the right permissions on my token and it doesn't work only when building on Github CIs or a Docker build 😬

**Comment by HugoRCD** [comment]
The build arguments were simply missing from the docker compose, thanks you @aatrooox !

```yaml
args:
   - NUXT_PRIVATE_GITHUB_TOKEN=${NUXT_PRIVATE_GITHUB_TOKEN}
 ```

**Comment by aatrooox** [comment]
I'm glad you solved the problem. 😊 @HugoRCD
