### ISSUE TITLE
Missing dependencies in `content` package

### ISSUE THREAD

**Issue by mainrs** [nuxt/content#776]
### Version
@nuxt/content: master

### Missing
`json5`

**Comment by aldy505** [comment]
This might be an old issue, but recently I got this while deploying to production.

The error reads:
```bash
 WARN  Module @nuxt/content not found. Please ensure @nuxt/content is in dependencies and installed.                                                                                                                               17:21:23


 FATAL  Cannot find module 'json5'                                                                                                                                                                                                 17:21:23
Require stack:
- /home/arcetid/nodejs/arcet.id/node_modules/@nuxt/content/lib/database.js

  Require stack:
  - node_modules/@nuxt/content/lib/database.js
  at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
  at Function.resolve (internal/modules/cjs/helpers.js:94:19)
  at p (node_modules/@nuxt/utils/node_modules/jiti/dist/jiti.js:1:45436)
  at v (node_modules/@nuxt/utils/node_modules/jiti/dist/jiti.js:1:46202)
  at node_modules/@nuxt/content/lib/database.js:5:15
  at v (node_modules/@nuxt/utils/node_modules/jiti/dist/jiti.js:1:47041)
  at node_modules/@nuxt/content/lib/index.js:9:18
  at Resolver.v [as _require] (node_modules/@nuxt/utils/node_modules/jiti/dist/jiti.js:1:47041)
  at Resolver.requireModule (node_modules/@nuxt/core/dist/core.js:381:29)
  at ModuleContainer.addModule (node_modules/@nuxt/core/dist/core.js:182:38)


   ╭────────────────────────────────────────────────────────────────────────────────╮
   │                                                                                │
   │   ✖ Nuxt Fatal Error                                                           │
   │                                                                                │
   │   Error: Cannot find module 'json5'                                            │
   │   Require stack:                                                               │
   │   - /home/arcetid/nodejs/arcet.id/node_modules/@nuxt/content/lib/database.js   │
   │                                                                                │
   ╰────────────────────────────────────────────────────────────────────────────────╯
```

But it's solved by just installing json5 explicitly. I'm running on a Node VM.

**Comment by Atinux** [comment]
Fixed in upcoming v2, for v1 you can always install `json5` next to it :blush:
