### ISSUE TITLE
`@nuxt/content-theme-docs` doesn't work with `target: 'server'`

### ISSUE THREAD

**Issue by danielroe** [nuxt/content#777]
### Version
@nuxt/content-theme-docs@0.10.1
nuxt@2.15.0

### Reproduction Link
https://github.com/ennoucas/demo-nuxt-content-vercel

### Steps to reproduce
1. add `target: 'server'` to `nuxt.config`
2. yarn && yarn build && yarn start

### What is Expected?
Site to display.

### What is actually happening?

```bash
 WARN  /my/repo/node_modules/@nuxt/content-theme-docs/src/content does not exist                    @nuxt/content 14:59:05

ℹ Parsed 0 files in 0,0 seconds                                                                                                              @nuxt/content 14:59:05

   ╭───────────────────────────────────────╮
   │                                       │
   │   Nuxt @ v2.15.0                      │
   │                                       │
   │   ▸ Environment: production           │
   │   ▸ Rendering:   server-side          │
   │   ▸ Target:      server               │
   │                                       │
   │   Memory usage: 41 MB (RSS: 117 MB)   │
   │                                       │
   │   Listening: http://localhost:3000/   │
   │                                       │
   ╰───────────────────────────────────────╯


 WARN  You can add a settings.json file inside the content/ folder to customize this theme.                                                                14:59:08


 ERROR  /en not found                                                                                                                                      14:59:08

  at QueryBuilder.fetch (node_modules/@nuxt/content/lib/query-builder.js:242:13)
  at Store.fetchCategories (node_modules/@nuxt/content-theme-docs/src/store/index.js:78:0)
  at Array.wrappedActionHandler (node_modules/vuex/dist/vuex.common.js:853:23)
  at Store.dispatch (node_modules/vuex/dist/vuex.common.js:518:15)
  at Store.boundDispatch [as dispatch] (node_modules/vuex/dist/vuex.common.js:408:21)
  at init (node_modules/@nuxt/content-theme-docs/src/plugins/init.js:5:0)
  at async createApp (.nuxt/index.js:268:0)
  at async module.exports.__webpack_exports__.default (.nuxt/server.js:81:0)

```

**Comment by farnabaz** [comment]
Closing this in favor of Docus. #726
