### ISSUE TITLE
Can't run nuxt after installing @nuxt/content

### ISSUE THREAD

**Issue by CaptainYouz** [nuxt/content#803]
### Version
@nuxt/content: ^1.13.1
nuxt: ^2.14.12

node: v12.16.2
npm: v7.5.2

macOs Big Sur: v11.2.1

### Description

When installing the module as explained in the doc (https://content.nuxtjs.org/installation), after I run an `npm run dev` command, I get this error:

```
 FATAL  Unsupported field type for full text search.                                       16:27:06

  at full_text_search_FullTextSearch.addDocument (node_modules/@lokidb/full-text-search/webpack:/@lokidb/full-text-search/packages/full-text-search/src/full_text_search.ts:59:17)
  at collection_Collection._add (node_modules/@lokidb/loki/webpack:/@lokidb/loki/packages/loki/src/collection.ts:963:30)
  at collection_Collection.insertOne (node_modules/@lokidb/loki/webpack:/@lokidb/loki/packages/loki/src/collection.ts:717:15)
  at collection_Collection.insert (node_modules/@lokidb/loki/webpack:/@lokidb/loki/packages/loki/src/collection.ts:656:19)
  at Database.insertFile (node_modules/@nuxt/content/lib/database.js:128:18)
  at async Promise.all (index 0)
  at Database.walk (node_modules/@nuxt/content/lib/database.js:86:5)
  at async Promise.all (index 0)
  at Database.walk (node_modules/@nuxt/content/lib/database.js:86:5)
  at Database.init (node_modules/@nuxt/content/lib/database.js:69:5)
  at ModuleContainer.module.exports (node_modules/@nuxt/content/lib/index.js:112:3)
  at ModuleContainer.addModule (node_modules/@nuxt/core/dist/core.js:239:20)
  at ModuleContainer.ready (node_modules/@nuxt/core/dist/core.js:55:5)
  at Nuxt._init (node_modules/@nuxt/core/dist/core.js:478:5)


   ╭─────────────────────────────────────────────────────────────╮
   │                                                             │
   │   ✖ Nuxt Fatal Error                                        │
   │                                                             │
   │   TypeError: Unsupported field type for full text search.   │
   │                                                             │
   ╰─────────────────────────────────────────────────────────────╯
```

### What is Expected?
The application to run

### What is actually happening?
The application crashs

**Comment by NozomuIkuta** [comment]
@CaptainYouz 

Could you share your `nuxt.config.js`?

It seems that you are setting something to `fullTextSearchFields`, while values of the properties in it is of other type than string or number (cf. #798).

**Comment by GuiguiWeb** [comment]
This error can be caused by writing json in yaml on [front matter](https://content.nuxtjs.org/writing/#front-matter).

It does not necessarily appear during the hot reload but at the complete restart of the server.

**Comment by GuiguiWeb** [comment]
> @CaptainYouz
> 
> Could you share your `nuxt.config.js`?
> 
> It seems that you are setting something to `fullTextSearchFields`, while values of the properties in it is of other type than string or number (cf. #798).
> 
> By default, `fullTextSearchFields` is set as `['title', 'description', 'slug', 'text']` ([doc](https://content.nuxtjs.org/configuration#fulltextsearchfields)).

Or modified a variable used on fullTextSearchFields like:
```
title:
  fr: Mon titre
  en: My title
```
