### ISSUE TITLE
operatorPackage[operator] is not a function  

### ISSUE THREAD

**Issue by ArthurDanjou** [nuxt/content#857]
### Version
@nuxt/content: 1.14.0
nuxt: 2.15.3

### Reproduction Link
https://github.com/arthurdanjou/artsite/tree/dev
Here is the page : https://github.com/ArthurDanjou/artsite/blob/dev/src/pages/projects/_slug.vue

### Steps to reproduce
Start with `yarn dev`, go to the project page then click on one project. 

### What is Expected?
I would like the skills to appear when clicking on a project

### What is actually happening?
When clicking the first time on a project, there is an error : 
```
 ERROR  operatorPackage[operator] is not a function                                                                                                                                                     12:41:59  
  at result_set_ResultSet.find (node_modules\@lokidb\loki\lokidb.loki.js:1418:50)
  at QueryBuilder.where (node_modules\@nuxt\content\lib\query-builder.js:73:29)
  at node_modules\@nuxt\content\lib\middleware.js:113:19
```. This error is present only one time for each project. When clicking again on the same project, the skills appear and all works

**Comment by ImmaZoni** [comment]
I am having a similar bug here. mine with with my /blog page and the tags

Replication Link - https://codesandbox.io/s/zealous-shirley-fr3bj
GitHub Link - https://github.com/ImmaZoni/nightfury-nuxt
